services:
  - type: web
    name: riks-contest
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: RIKS_HANDLE
        value: Aanant
      - key: RIKS_PASSWORD
        sync: false
