"""INI-CET MCQ bank — recall-style, tagged by topic."""

from __future__ import annotations

QUESTIONS = [
    {
        "id": "q-a-upper-1",
        "topic_id": "a-upper",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Erb's point injury affects which roots?",
        "options": ["C5-C6", "C8-T1", "C7-T1", "C3-C4"],
        "answer": "C5-C6",
        "explanation": "Erb's palsy = upper trunk C5-C6.",
    },
    {
        "id": "q-a-upper-2",
        "topic_id": "a-upper",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Which nerve is most vulnerable in axillary dislocation?",
        "options": ["Axillary nerve", "Radial nerve", "Ulnar nerve", "Median nerve"],
        "answer": "Axillary nerve",
        "explanation": "Axillary nerve wraps surgical neck of humerus.",
    },
    {
        "id": "q-a-lower-1",
        "topic_id": "a-lower",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Foot drop is caused by injury to:",
        "options": ["Common peroneal nerve", "Tibial nerve", "Femoral nerve", "Obturator nerve"],
        "answer": "Common peroneal nerve",
        "explanation": "Common peroneal → dorsiflexion loss.",
    },
    {
        "id": "q-a-lower-2",
        "topic_id": "a-lower",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Popliteal fossa boundary — which is medial?",
        "options": ["Sartorius", "Biceps femoris", "Semimembranosus", "Gastrocnemius"],
        "answer": "Semimembranosus",
        "explanation": "Semimembranosus forms medial border.",
    },
    {
        "id": "q-a-thorax-1",
        "topic_id": "a-thorax",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Cardiac tamponade — which chamber wall is thinnest?",
        "options": ["Right ventricle", "Left ventricle", "Right atrium", "Left atrium"],
        "answer": "Right ventricle",
        "explanation": "RV wall is thinnest; fills in tamponade.",
    },
    {
        "id": "q-a-thorax-2",
        "topic_id": "a-thorax",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Aortic arch gives rise to all EXCEPT:",
        "options": ["Brachiocephalic trunk", "Left common carotid", "Left subclavian", "Right subclavian"],
        "answer": "Right subclavian",
        "explanation": "Right subclavian from brachiocephalic, not arch directly.",
    },
    {
        "id": "q-p-general-1",
        "topic_id": "p-general",
        "subject_id": "physiology",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Resting membrane potential is primarily due to:",
        "options": ["K+ permeability", "Na+ permeability", "Cl- permeability", "Ca2+ pump"],
        "answer": "K+ permeability",
        "explanation": "Dominant K+ leak sets RMP near EK.",
    },
    {
        "id": "q-p-general-2",
        "topic_id": "p-general",
        "subject_id": "physiology",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Action potential peak is driven by:",
        "options": ["Na+ influx", "K+ efflux", "Ca2+ influx only", "Cl- influx"],
        "answer": "Na+ influx",
        "explanation": "Rapid Na+ channels depolarise to peak.",
    },
    {
        "id": "q-a-head-1",
        "topic_id": "a-head",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Facial nerve exits skull via:",
        "options": ["Stylomastoid foramen", "Foramen ovale", "Foramen rotundum", "Jugular foramen"],
        "answer": "Stylomastoid foramen",
        "explanation": "CN VII motor exit is stylomastoid.",
    },
    {
        "id": "q-a-head-2",
        "topic_id": "a-head",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Parotid duct opens opposite:",
        "options": ["Upper 2nd molar", "Lower 1st molar", "Upper incisor", "Lower canine"],
        "answer": "Upper 2nd molar",
        "explanation": "Stensen's duct at buccal mucosa opposite 2nd upper molar.",
    },
    {
        "id": "q-a-neuro-1",
        "topic_id": "a-neuro",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Lateral medullary syndrome spares:",
        "options": ["Face sensation", "Spinothalamic pain/temp", "Horner's syndrome", "Dysphagia"],
        "answer": "Face sensation",
        "explanation": "Spinal trigeminal nucleus spared in Wallenberg.",
    },
    {
        "id": "q-a-neuro-2",
        "topic_id": "a-neuro",
        "subject_id": "anatomy",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Internal capsule — pure motor stroke usually involves:",
        "options": ["Posterior limb", "Genu only", "Anterior limb", "Retrolentiform"],
        "answer": "Posterior limb",
        "explanation": "Corticospinal tract in posterior limb.",
    },
    {
        "id": "q-p-cvs-1",
        "topic_id": "p-cvs",
        "subject_id": "physiology",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Second heart sound is due to:",
        "options": ["Aortic + pulmonary valve closure", "Mitral closure", "Tricuspid closure", "Ventricular filling"],
        "answer": "Aortic + pulmonary valve closure",
        "explanation": "S2 = A2 + P2 at end of ejection.",
    },
    {
        "id": "q-p-cvs-2",
        "topic_id": "p-cvs",
        "subject_id": "physiology",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Baroreceptor reflex increases HR via:",
        "options": ["Decreased vagal tone", "Increased vagal tone", "Beta blockade", "Alpha stimulation"],
        "answer": "Decreased vagal tone",
        "explanation": "Hypotension → less vagal → tachycardia.",
    },
    {
        "id": "q-p-resp-1",
        "topic_id": "p-resp",
        "subject_id": "physiology",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "FEV1/FVC ratio reduced in:",
        "options": ["Obstructive disease", "Restrictive disease", "Normal lungs", "Pulmonary fibrosis only"],
        "answer": "Obstructive disease",
        "explanation": "Obstruction lowers FEV1 disproportionately.",
    },
    {
        "id": "q-p-resp-2",
        "topic_id": "p-resp",
        "subject_id": "physiology",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Hypoxic pulmonary vasoconstriction is:",
        "options": ["Local response to low alveolar PO2", "Systemic hypoxia only", "CO2 driven", "Absent in lungs"],
        "answer": "Local response to low alveolar PO2",
        "explanation": "Matches V/Q — classic physiology.",
    },
    {
        "id": "q-b-metab-1",
        "topic_id": "b-metab",
        "subject_id": "biochem",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Rate-limiting enzyme of glycolysis:",
        "options": ["Phosphofructokinase-1", "Hexokinase", "Pyruvate kinase", "Aldolase"],
        "answer": "Phosphofructokinase-1",
        "explanation": "PFK-1 is main control point.",
    },
    {
        "id": "q-b-metab-2",
        "topic_id": "b-metab",
        "subject_id": "biochem",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Vitamin B1 deficiency affects:",
        "options": ["Pyruvate dehydrogenase", "Glycogen synthase", "HMG-CoA reductase", "Catalase"],
        "answer": "Pyruvate dehydrogenase",
        "explanation": "Thiamine cofactor for PDH — Wernicke risk.",
    },
    {
        "id": "q-b-clinical-1",
        "topic_id": "b-clinical",
        "subject_id": "biochem",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "CK-MB is most specific for:",
        "options": ["Myocardial injury", "Liver injury", "Muscle trauma only", "Brain injury"],
        "answer": "Myocardial injury",
        "explanation": "CK-MB historically cardiac-specific.",
    },
    {
        "id": "q-b-clinical-2",
        "topic_id": "b-clinical",
        "subject_id": "biochem",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Metabolic acidosis with high anion gap — NOT:",
        "options": ["Diarrhoea", "DKA", "Lactic acidosis", "Uremia"],
        "answer": "Diarrhoea",
        "explanation": "Diarrhoea → normal AG hyperchloremic acidosis.",
    },
    {
        "id": "q-ph-general-1",
        "topic_id": "ph-general",
        "subject_id": "pharma",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "First-pass metabolism mainly occurs in:",
        "options": ["Liver", "Kidney", "Lungs only", "Brain"],
        "answer": "Liver",
        "explanation": "Oral drugs hit hepatic first-pass.",
    },
    {
        "id": "q-ph-general-2",
        "topic_id": "ph-general",
        "subject_id": "pharma",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Therapeutic index is:",
        "options": ["TD50/ED50", "ED50/TD50", "LD50/ED50", "ED50/LD50"],
        "answer": "LD50/ED50",
        "explanation": "TI = LD50/ED50 — safety margin.",
    },
    {
        "id": "q-ph-ans-1",
        "topic_id": "ph-ans",
        "subject_id": "pharma",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Atropine blocks:",
        "options": ["Muscarinic receptors", "Nicotinic receptors", "Alpha-1", "Beta-2"],
        "answer": "Muscarinic receptors",
        "explanation": "Antimuscarinic — dry mouth, tachycardia.",
    },
    {
        "id": "q-ph-ans-2",
        "topic_id": "ph-ans",
        "subject_id": "pharma",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Phenylephrine is primarily:",
        "options": ["Alpha-1 agonist", "Beta-2 agonist", "Mixed agonist", "Alpha-2 antagonist"],
        "answer": "Alpha-1 agonist",
        "explanation": "Pure alpha-1 → vasoconstriction.",
    },
    {
        "id": "q-ph-cvsab-1",
        "topic_id": "ph-cvsab",
        "subject_id": "pharma",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "First-line HTN in young non-black patient often:",
        "options": ["ACE inhibitor", "Thiazide alone always", "Beta blocker first", "Alpha blocker"],
        "answer": "ACE inhibitor",
        "explanation": "Guidelines favour ACEi/ARB in many groups.",
    },
    {
        "id": "q-ph-cvsab-2",
        "topic_id": "ph-cvsab",
        "subject_id": "pharma",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Penicillin allergy — cross-reactivity highest with:",
        "options": ["Cephalosporins (early gens)", "Aminoglycosides", "Fluoroquinolones", "Metronidazole"],
        "answer": "Cephalosporins (early gens)",
        "explanation": "Beta-lactam ring similarity.",
    },
    {
        "id": "q-pa-general-1",
        "topic_id": "pa-general",
        "subject_id": "pathology",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Caseous necrosis is characteristic of:",
        "options": ["Tuberculosis", "Infarct", "Abscess bacterial", "Fat necrosis"],
        "answer": "Tuberculosis",
        "explanation": "Granulomatous TB → caseous necrosis.",
    },
    {
        "id": "q-pa-general-2",
        "topic_id": "pa-general",
        "subject_id": "pathology",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "APC gene mutation associated with:",
        "options": ["FAP", "Li-Fraumeni", "BRCA1", "NF1"],
        "answer": "FAP",
        "explanation": "APC → familial adenomatous polyposis.",
    },
    {
        "id": "q-pa-hema-1",
        "topic_id": "pa-hema",
        "subject_id": "pathology",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Reed-Sternberg cells are seen in:",
        "options": ["Hodgkin lymphoma", "DLBCL", "CLL", "Multiple myeloma"],
        "answer": "Hodgkin lymphoma",
        "explanation": "Classic RS cells in Hodgkin.",
    },
    {
        "id": "q-pa-hema-2",
        "topic_id": "pa-hema",
        "subject_id": "pathology",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "ITP mechanism:",
        "options": ["Anti-platelet antibodies", "DIC", "Splenic sequestration only", "Vitamin K deficiency"],
        "answer": "Anti-platelet antibodies",
        "explanation": "Autoimmune platelet destruction.",
    },
    {
        "id": "q-pa-systemic-1",
        "topic_id": "pa-systemic",
        "subject_id": "pathology",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Crescentic glomerulonephritis — key finding:",
        "options": ["Rapidly progressive GN", "Minimal change", "IgA mesangial only", "Amyloid"],
        "answer": "Rapidly progressive GN",
        "explanation": "Crescents = RPGN pattern.",
    },
    {
        "id": "q-pa-systemic-2",
        "topic_id": "pa-systemic",
        "subject_id": "pathology",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Cirrhosis histology shows:",
        "options": ["Nodules + fibrosis", "Caseating granulomas", "Fat only", "Amyloid deposits"],
        "answer": "Nodules + fibrosis",
        "explanation": "Regenerating nodules in fibrous bands.",
    },
    {
        "id": "q-mi-bacteria-1",
        "topic_id": "mi-bacteria",
        "subject_id": "micro",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Mantoux test measures:",
        "options": ["Cell-mediated immunity to TB", "Humoral immunity", "Neutrophil function", "Complement"],
        "answer": "Cell-mediated immunity to TB",
        "explanation": "Type IV hypersensitivity to PPD.",
    },
    {
        "id": "q-mi-bacteria-2",
        "topic_id": "mi-bacteria",
        "subject_id": "micro",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Coagulase-positive Staphylococcus:",
        "options": ["S. aureus", "S. epidermidis", "Strep pyogenes", "Enterococcus"],
        "answer": "S. aureus",
        "explanation": "Coagulase distinguishes aureus.",
    },
    {
        "id": "q-mi-virology-1",
        "topic_id": "mi-virology",
        "subject_id": "micro",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "HIV entry requires CD4 and:",
        "options": ["CCR5/CXCR4", "CD8", "CD19", "CD16"],
        "answer": "CCR5/CXCR4",
        "explanation": "Co-receptors for gp120 binding.",
    },
    {
        "id": "q-mi-virology-2",
        "topic_id": "mi-virology",
        "subject_id": "micro",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "India ink stain used for:",
        "options": ["Cryptococcus", "Candida", "Aspergillus", "Histoplasma"],
        "answer": "Cryptococcus",
        "explanation": "Capsule visualised — CSF meningitis.",
    },
    {
        "id": "q-me-cardio-1",
        "topic_id": "me-cardio",
        "subject_id": "medicine",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "STEMI — door-to-balloon target historically:",
        "options": ["90 minutes", "30 minutes", "6 hours", "24 hours"],
        "answer": "90 minutes",
        "explanation": "Reperfusion time critical in STEMI.",
    },
    {
        "id": "q-me-cardio-2",
        "topic_id": "me-cardio",
        "subject_id": "medicine",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Mitral stenosis murmur:",
        "options": ["Diastolic rumble at apex", "Holosystolic at apex", "Ejection click", "Aortic crescendo-decrescendo"],
        "answer": "Diastolic rumble at apex",
        "explanation": "MS — low-pitched diastolic at apex.",
    },
    {
        "id": "q-me-endo-1",
        "topic_id": "me-endo",
        "subject_id": "medicine",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "DKA — initial fluid of choice:",
        "options": ["Normal saline", "Half-normal saline first", "D5W only", "Ringers lactate always"],
        "answer": "Normal saline",
        "explanation": "Volume resuscitation with NS first line.",
    },
    {
        "id": "q-me-endo-2",
        "topic_id": "me-endo",
        "subject_id": "medicine",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Graves disease — pathognomonic eye sign:",
        "options": ["Lid lag / retraction", "Ptosis only", "Horner syndrome", "Fixed dilated pupil"],
        "answer": "Lid lag / retraction",
        "explanation": "Thyroid eye disease features.",
    },
    {
        "id": "q-me-nephro-1",
        "topic_id": "me-nephro",
        "subject_id": "medicine",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Hepatorenal syndrome — key feature:",
        "options": ["Functional renal failure in cirrhosis", "Obstructive uropathy", "GN with RBC casts", "ATN from sepsis only"],
        "answer": "Functional renal failure in cirrhosis",
        "explanation": "Renal vasoconstriction in advanced liver disease.",
    },
    {
        "id": "q-me-nephro-2",
        "topic_id": "me-nephro",
        "subject_id": "medicine",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Acute pancreatitis — best initial imaging:",
        "options": ["CT abdomen", "Ultrasound", "MRI always", "X-ray only"],
        "answer": "Ultrasound",
        "explanation": "US for gallstones; CT if diagnostic doubt.",
    },
    {
        "id": "q-ps-epi-1",
        "topic_id": "ps-epi",
        "subject_id": "psm",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Sensitivity measures:",
        "options": ["True positives / all diseased", "True negatives / all healthy", "PPV", "Specificity"],
        "answer": "True positives / all diseased",
        "explanation": "SnNout — rule OUT if negative.",
    },
    {
        "id": "q-ps-epi-2",
        "topic_id": "ps-epi",
        "subject_id": "psm",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Incidence measures:",
        "options": ["New cases / person-time", "Existing cases / population", "Deaths only", "Prevalence always"],
        "answer": "New cases / person-time",
        "explanation": "Incidence = new events over time.",
    },
    {
        "id": "q-ps-programs-1",
        "topic_id": "ps-programs",
        "subject_id": "psm",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "RNTCP now integrated as:",
        "options": ["NTEP (TB elimination)", "NLEP", "RCH only", "NVBDCP alone"],
        "answer": "NTEP (TB elimination)",
        "explanation": "Revised national TB elimination programme.",
    },
    {
        "id": "q-ps-programs-2",
        "topic_id": "ps-programs",
        "subject_id": "psm",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Mission Indradhanush targets:",
        "options": ["Full immunisation", "TB only", "HIV only", "Malaria eradication"],
        "answer": "Full immunisation",
        "explanation": "Intensified immunisation drive.",
    },
    {
        "id": "q-su-general-1",
        "topic_id": "su-general",
        "subject_id": "surgery",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "McBurney's point is:",
        "options": ["1/3 from ASIS to umbilicus", "Midline epigastrium", "Right hypochondrium", "Left iliac fossa"],
        "answer": "1/3 from ASIS to umbilicus",
        "explanation": "Classic appendicitis tenderness.",
    },
    {
        "id": "q-su-general-2",
        "topic_id": "su-general",
        "subject_id": "surgery",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Indirect inguinal hernia passes through:",
        "options": ["Deep inguinal ring", "Hesselbach triangle", "Femoral canal", "Linea alba"],
        "answer": "Deep inguinal ring",
        "explanation": "Indirect = lateral to epigastric vessels.",
    },
    {
        "id": "q-su-gi-1",
        "topic_id": "su-gi",
        "subject_id": "surgery",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Boerhaave syndrome is:",
        "options": ["Esophageal rupture", "Gastric ulcer perf", "Appendicitis", "Pancreatitis"],
        "answer": "Esophageal rupture",
        "explanation": "Full-thickness esophageal tear — Mackler triad.",
    },
    {
        "id": "q-su-gi-2",
        "topic_id": "su-gi",
        "subject_id": "surgery",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Most common cause of small bowel obstruction in adults:",
        "options": ["Adhesions", "Hernia always", "Volvulus first", "Intussusception"],
        "answer": "Adhesions",
        "explanation": "Post-op adhesions commonest SBO cause.",
    },
    {
        "id": "q-or-trauma-1",
        "topic_id": "or-trauma",
        "subject_id": "ortho",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Colles fracture is:",
        "options": ["Distal radius dorsal angulation", "Scaphoid waist", "Boxer's fracture", "Monteggia"],
        "answer": "Distal radius dorsal angulation",
        "explanation": "FOOSH injury — dinner fork deformity.",
    },
    {
        "id": "q-or-trauma-2",
        "topic_id": "or-trauma",
        "subject_id": "ortho",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Compartment syndrome — earliest sign:",
        "options": ["Pain out of proportion", "Pulselessness", "Paralysis first", "Pallor only"],
        "answer": "Pain out of proportion",
        "explanation": "Pain on passive stretch early; 6 Ps later.",
    },
    {
        "id": "q-or-spine-1",
        "topic_id": "or-spine",
        "subject_id": "ortho",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Cauda equina — emergency presentation:",
        "options": ["Saddle anesthesia + urinary retention", "Unilateral sciatica only", "Mild backache", "Hip pain only"],
        "answer": "Saddle anesthesia + urinary retention",
        "explanation": "Surgical decompression emergency.",
    },
    {
        "id": "q-or-spine-2",
        "topic_id": "or-spine",
        "subject_id": "ortho",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Osteoarthritis — characteristic X-ray:",
        "options": ["Joint space narrowing + osteophytes", "Punched-out erosions", "Periosteal reaction only", "Soft tissue calcification only"],
        "answer": "Joint space narrowing + osteophytes",
        "explanation": "Degenerative OA pattern.",
    },
    {
        "id": "q-ob-obs-1",
        "topic_id": "ob-obs",
        "subject_id": "obg",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Eclampsia is defined by:",
        "options": ["Seizures in preeclampsia", "HTN alone", "Proteinuria only", "Oliguria only"],
        "answer": "Seizures in preeclampsia",
        "explanation": "Preeclampsia + convulsions = eclampsia.",
    },
    {
        "id": "q-ob-obs-2",
        "topic_id": "ob-obs",
        "subject_id": "obg",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Most common cause of PPH:",
        "options": ["Uterine atony", "Retained placenta always", "Vaginal tear first", "Coagulopathy most common"],
        "answer": "Uterine atony",
        "explanation": "Atony is leading cause of PPH.",
    },
    {
        "id": "q-ob-gyn-1",
        "topic_id": "ob-gyn",
        "subject_id": "obg",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "PCOS — Rotterdam criterion includes:",
        "options": ["Oligo-anovulation + hyperandrogenism + polycystic ovaries", "Endometriosis", "Fibroids", "Cervical dysplasia"],
        "answer": "Oligo-anovulation + hyperandrogenism + polycystic ovaries",
        "explanation": "2 of 3 Rotterdam criteria.",
    },
    {
        "id": "q-ob-gyn-2",
        "topic_id": "ob-gyn",
        "subject_id": "obg",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "CIN 3 management often:",
        "options": ["LEEP / conisation", "Antibiotics", "Hysterectomy always first", "Observation only"],
        "answer": "LEEP / conisation",
        "explanation": "Treat high-grade CIN to prevent invasion.",
    },
    {
        "id": "q-pe-neonatal-1",
        "topic_id": "pe-neonatal",
        "subject_id": "peds",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Physiological jaundice peaks at:",
        "options": ["Day 3-5", "Day 1 only", "Day 14 always", "Never in term babies"],
        "answer": "Day 3-5",
        "explanation": "Benign unconjugated jaundice peaks day 3-5.",
    },
    {
        "id": "q-pe-neonatal-2",
        "topic_id": "pe-neonatal",
        "subject_id": "peds",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Rh hemolytic disease — first affected pregnancy:",
        "options": ["Usually milder in first", "Always stillbirth first", "Never affects first", "Only affects second always"],
        "answer": "Usually milder in first",
        "explanation": "Sensitisation builds; later pregnancies worse.",
    },
    {
        "id": "q-pe-infections-1",
        "topic_id": "pe-infections",
        "subject_id": "peds",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Kawasaki disease — treatment:",
        "options": ["IVIG + aspirin", "Antibiotics alone", "Steroids only", "No treatment"],
        "answer": "IVIG + aspirin",
        "explanation": "Prevent coronary aneurysms.",
    },
    {
        "id": "q-pe-infections-2",
        "topic_id": "pe-infections",
        "subject_id": "peds",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Measles complication — most feared:",
        "options": ["SSPE / pneumonia", "Otitis only", "Simple rash", "Benign course always"],
        "answer": "SSPE / pneumonia",
        "explanation": "Pneumonia common killer; SSPE late.",
    },
    {
        "id": "q-eo-ent-1",
        "topic_id": "eo-ent",
        "subject_id": "ent_ophth",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Cholesteatoma is:",
        "options": ["Keratinising squamous epithelium in middle ear", "External otitis", "Benign parotid tumour", "Vestibular schwannoma"],
        "answer": "Keratinising squamous epithelium in middle ear",
        "explanation": "Destructive middle ear disease.",
    },
    {
        "id": "q-eo-ent-2",
        "topic_id": "eo-ent",
        "subject_id": "ent_ophth",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "BPPV treated with:",
        "options": ["Epley manoeuvre", "Antibiotics", "Mastoidectomy", "Antihistamines long-term only"],
        "answer": "Epley manoeuvre",
        "explanation": "Canalith repositioning for posterior canal BPPV.",
    },
    {
        "id": "q-eo-ophth-1",
        "topic_id": "eo-ophth",
        "subject_id": "ent_ophth",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Acute angle closure glaucoma — drug to avoid:",
        "options": ["Atropine / mydriatics", "Pilocarpine", "Acetazolamide", "Timolol"],
        "answer": "Atropine / mydriatics",
        "explanation": "Mydriatics worsen angle closure.",
    },
    {
        "id": "q-eo-ophth-2",
        "topic_id": "eo-ophth",
        "subject_id": "ent_ophth",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Red flag in red eye:",
        "options": ["Pain + decreased vision", "Itching only", "Watering only", "Mild discharge alone"],
        "answer": "Pain + decreased vision",
        "explanation": "Painful vision loss — urgent referral.",
    },
    {
        "id": "q-fo-legal-1",
        "topic_id": "fo-legal",
        "subject_id": "forensic",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Pupil size in opiate overdose:",
        "options": ["Pinpoint", "Mid-dilated", "Fully dilated", "Unequal always"],
        "answer": "Pinpoint",
        "explanation": "Miosis classic in opioid poisoning.",
    },
    {
        "id": "q-fo-legal-2",
        "topic_id": "fo-legal",
        "subject_id": "forensic",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Rigor mortis starts at:",
        "options": ["Small muscles of jaw/face", "Large limb muscles first", "Heart first", "Simultaneously everywhere"],
        "answer": "Small muscles of jaw/face",
        "explanation": "Starts headward, spreads caudally.",
    },
    {
        "id": "q-fo-psych-1",
        "topic_id": "fo-psych",
        "subject_id": "forensic",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "First-line for major depression often:",
        "options": ["SSRI", "Typical antipsychotic", "Lithium first", "Benzodiazepine monotherapy"],
        "answer": "SSRI",
        "explanation": "SSRIs first-line unless contraindicated.",
    },
    {
        "id": "q-fo-psych-2",
        "topic_id": "fo-psych",
        "subject_id": "forensic",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Negative symptoms prominent in:",
        "options": ["Schizophrenia", "Mania", "GAD", "OCD"],
        "answer": "Schizophrenia",
        "explanation": "Affective flattening, avolition, alogia.",
    },
    {
        "id": "q-me-revision-1",
        "topic_id": "me-revision",
        "subject_id": "medicine",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Drug of choice for acute severe asthma:",
        "options": ["Salbutamol nebulisation", "Oral antihistamine", "Codeine", "Beta blocker"],
        "answer": "Salbutamol nebulisation",
        "explanation": "Short-acting beta-2 agonist first line.",
    },
    {
        "id": "q-me-revision-2",
        "topic_id": "me-revision",
        "subject_id": "medicine",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Hyponatremia with SIADH — fluid restriction:",
        "options": ["First-line often", "Contraindicated always", "Give hypertonic saline always first", "No role"],
        "answer": "First-line often",
        "explanation": "Mild-moderate SIADH → fluid restriction.",
    },
    {
        "id": "q-ph-revision-1",
        "topic_id": "ph-revision",
        "subject_id": "pharma",
        "source": "recall",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Warfarin mechanism:",
        "options": ["Vitamin K epoxide reductase inhibition", "Direct thrombin inhibition", "Platelet aggregation block", "Factor Xa direct only"],
        "answer": "Vitamin K epoxide reductase inhibition",
        "explanation": "Reduces functional II, VII, IX, X.",
    },
    {
        "id": "q-ph-revision-2",
        "topic_id": "ph-revision",
        "subject_id": "pharma",
        "source": "recall",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.85,
        "marks": 1,
        "type": "mcq",
        "text": "Metformin contraindicated in:",
        "options": ["Severe renal impairment", "Mild obesity", "Type 2 DM always safe", "PCOS"],
        "answer": "Severe renal impairment",
        "explanation": "Lactic acidosis risk if eGFR very low.",
    },
]


def questions_for_topic(topic_id: str) -> list:
    return [q for q in QUESTIONS if q["topic_id"] == topic_id]


def question_by_id(question_id: str) -> dict:
    return next(q for q in QUESTIONS if q["id"] == question_id)