"""Question bank: PYQ-style, NCERT, and model paper items tagged for difficulty and probability."""

from __future__ import annotations

# difficulty: 1 easy, 2 medium, 3 hard
# source: pyq | ncert | model
QUESTIONS = [
    # Maths — Quadratic
    {
        "id": "q-m-quad-1",
        "topic_id": "m-quad",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2023,
        "difficulty": 1,
        "probability": 0.95,
        "marks": 2,
        "type": "mcq",
        "text": "The roots of the equation x² − 3x − 10 = 0 are",
        "options": ["2 and 5", "−2 and 5", "2 and −5", "−2 and −5"],
        "answer": "−2 and 5",
        "explanation": "x² − 3x − 10 = (x − 5)(x + 2). Roots are 5 and −2.",
    },
    {
        "id": "q-m-quad-2",
        "topic_id": "m-quad",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.88,
        "marks": 3,
        "type": "short",
        "text": "Find the nature of the roots of 2x² − 6x + 3 = 0 without solving.",
        "answer": "real and distinct",
        "explanation": "D = b² − 4ac = 36 − 24 = 12 > 0, so two distinct real roots.",
        "keywords": ["discriminant", "d=12", "real", "distinct", "positive"],
    },
    {
        "id": "q-m-quad-3",
        "topic_id": "m-quad",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.80,
        "marks": 4,
        "type": "short",
        "text": "A train travels 360 km at a uniform speed. If the speed had been 5 km/h more, it would have taken 1 hour less. Find the original speed.",
        "answer": "40",
        "explanation": "Let speed be x. 360/x − 360/(x+5) = 1 → x² + 5x − 1800 = 0 → x = 40 km/h.",
        "keywords": ["40"],
    },
    # Maths — AP
    {
        "id": "q-m-ap-1",
        "topic_id": "m-ap",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 1,
        "probability": 0.92,
        "marks": 2,
        "type": "mcq",
        "text": "The 10th term of the AP 5, 8, 11, 14, … is",
        "options": ["32", "35", "30", "29"],
        "answer": "32",
        "explanation": "a = 5, d = 3, a₁₀ = 5 + 9×3 = 32.",
    },
    {
        "id": "q-m-ap-2",
        "topic_id": "m-ap",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2022,
        "difficulty": 2,
        "probability": 0.90,
        "marks": 3,
        "type": "short",
        "text": "How many two-digit numbers are divisible by 3?",
        "answer": "30",
        "explanation": "12, 15, …, 99. n = ((99−12)/3) + 1 = 30.",
        "keywords": ["30"],
    },
    {
        "id": "q-m-ap-3",
        "topic_id": "m-ap",
        "subject_id": "maths",
        "source": "model",
        "difficulty": 2,
        "probability": 0.85,
        "marks": 4,
        "type": "short",
        "text": "The sum of the first n terms of an AP is 3n² + 4n. Find the 12th term.",
        "answer": "73",
        "explanation": "aₙ = Sₙ − Sₙ₋₁ = (3n²+4n) − (3(n−1)²+4(n−1)) = 6n + 1. a₁₂ = 73.",
        "keywords": ["73"],
    },
    # Maths — Trigonometry
    {
        "id": "q-m-trig-1",
        "topic_id": "m-trig",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2023,
        "difficulty": 1,
        "probability": 0.97,
        "marks": 2,
        "type": "mcq",
        "text": "The value of sin 30° · cos 60° is",
        "options": ["1", "1/2", "1/4", "√3/4"],
        "answer": "1/4",
        "explanation": "sin 30° = 1/2, cos 60° = 1/2, product = 1/4.",
    },
    {
        "id": "q-m-trig-2",
        "topic_id": "m-trig",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.93,
        "marks": 3,
        "type": "short",
        "text": "Prove or verify: 1 + tan² A = sec² A for A = 45°.",
        "answer": "identity holds",
        "explanation": "tan 45° = 1, sec 45° = √2. 1 + 1 = 2 and (√2)² = 2.",
        "keywords": ["2", "identity", "holds", "equal"],
    },
    {
        "id": "q-m-trig-3",
        "topic_id": "m-trig",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2024,
        "difficulty": 3,
        "probability": 0.78,
        "marks": 4,
        "type": "short",
        "text": "If tan(A + B) = √3 and tan(A − B) = 1/√3, 0 < A + B ≤ 90°, A > B, find A and B.",
        "answer": "A=45, B=15",
        "explanation": "A+B = 60°, A−B = 30° → A = 45°, B = 15°.",
        "keywords": ["45", "15"],
    },
    {
        "id": "q-m-trigapp-1",
        "topic_id": "m-trigapp",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.90,
        "marks": 4,
        "type": "short",
        "text": "A 1.5 m tall boy is at some distance from a 30 m tall building. The angle of elevation from his eye to the top of the building increases from 30° to 60° as he walks towards it. Find how far he walked.",
        "answer": "19.05 m or 10√3 m",
        "explanation": "Height above eye = 28.5 m. Distances 28.5√3 and 28.5/√3. Walked = 28.5(√3 − 1/√3) = 19√3 ≈ 19.05? Wait: 28.5 × (2/√3) = 19√3 ≈ 32.9. Correct: 28.5(√3 − 1/√3) = 28.5 × 2/√3 = 19√3 m.",
        "keywords": ["19", "sqrt", "√3", "32"],
    },
    # Maths — Linear
    {
        "id": "q-m-linear-1",
        "topic_id": "m-linear",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2023,
        "difficulty": 1,
        "probability": 0.90,
        "marks": 2,
        "type": "mcq",
        "text": "The pair 2x + 3y = 5 and 4x + 6y = 10 represents",
        "options": ["intersecting lines", "parallel lines", "coincident lines", "no geometric meaning"],
        "answer": "coincident lines",
        "explanation": "a1/a2 = b1/b2 = c1/c2 = 1/2, so infinitely many solutions (coincident).",
    },
    {
        "id": "q-m-linear-2",
        "topic_id": "m-linear",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.86,
        "marks": 3,
        "type": "short",
        "text": "Solve: x + y = 5 and 2x − 3y = 4.",
        "answer": "x=19/5, y=6/5",
        "explanation": "From first y = 5 − x. 2x − 3(5−x) = 4 → 5x = 19 → x = 19/5, y = 6/5.",
        "keywords": ["19/5", "3.8", "6/5", "1.2"],
    },
    # Maths — Probability & Stats
    {
        "id": "q-m-prob-1",
        "topic_id": "m-prob",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2024,
        "difficulty": 1,
        "probability": 0.90,
        "marks": 2,
        "type": "mcq",
        "text": "A die is thrown once. Probability of getting a prime number is",
        "options": ["1/2", "1/3", "1/6", "2/3"],
        "answer": "1/2",
        "explanation": "Primes on a die: 2, 3, 5 → 3/6 = 1/2.",
    },
    {
        "id": "q-m-stats-1",
        "topic_id": "m-stats",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.88,
        "marks": 3,
        "type": "short",
        "text": "The mean of 5, 7, 9, 11, x is 10. Find x.",
        "answer": "18",
        "explanation": "(5+7+9+11+x)/5 = 10 → 32 + x = 50 → x = 18.",
        "keywords": ["18"],
    },
    {
        "id": "q-m-coord-1",
        "topic_id": "m-coord",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2022,
        "difficulty": 2,
        "probability": 0.86,
        "marks": 3,
        "type": "short",
        "text": "Find the distance between A(2, −3) and B(−2, 3).",
        "answer": "2√13",
        "explanation": "√[(2+2)² + (−3−3)²] = √(16+36) = √52 = 2√13.",
        "keywords": ["2√13", "sqrt(52)", "7.21"],
    },
    {
        "id": "q-m-circle-1",
        "topic_id": "m-circle",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.84,
        "marks": 3,
        "type": "short",
        "text": "A tangent at a point of a circle is perpendicular to the radius through the point of contact. If radius is 7 cm and tangent from an external point is 24 cm, find the distance of that point from the centre.",
        "answer": "25 cm",
        "explanation": "Right triangle: 7² + 24² = 49 + 576 = 625 = 25².",
        "keywords": ["25"],
    },
    {
        "id": "q-m-tri-1",
        "topic_id": "m-tri",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2023,
        "difficulty": 2,
        "probability": 0.88,
        "marks": 3,
        "type": "mcq",
        "text": "In ΔABC ~ ΔDEF, AB/DE = 2/3. If area(ΔABC) = 36 cm², area(ΔDEF) is",
        "options": ["54 cm²", "81 cm²", "24 cm²", "72 cm²"],
        "answer": "81 cm²",
        "explanation": "Ratio of areas = (2/3)² = 4/9. 36 / area = 4/9 → area = 81.",
    },
    {
        "id": "q-m-vol-1",
        "topic_id": "m-vol",
        "subject_id": "maths",
        "source": "model",
        "difficulty": 2,
        "probability": 0.82,
        "marks": 4,
        "type": "short",
        "text": "A solid is a hemisphere surmounted by a cone of same radius 3.5 cm. Height of cone is 7 cm. Find the volume (use π = 22/7).",
        "answer": "179.67 cm³ or 539/3",
        "explanation": "V = (2/3)πr³ + (1/3)πr²h = (2/3)(22/7)(3.5)³ + (1/3)(22/7)(3.5)²(7) ≈ 89.83 + 89.83 = 179.67 cm³.",
        "keywords": ["179", "180", "539"],
    },
    # Science — Life processes
    {
        "id": "q-s-life-1",
        "topic_id": "s-life",
        "subject_id": "science",
        "source": "pyq",
        "year": 2024,
        "difficulty": 1,
        "probability": 0.96,
        "marks": 2,
        "type": "mcq",
        "text": "The breakdown of pyruvate to give carbon dioxide, water and energy takes place in",
        "options": ["cytoplasm", "mitochondria", "chloroplast", "nucleus"],
        "answer": "mitochondria",
        "explanation": "Aerobic respiration: pyruvate is oxidised in mitochondria.",
    },
    {
        "id": "q-s-life-2",
        "topic_id": "s-life",
        "subject_id": "science",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.90,
        "marks": 3,
        "type": "short",
        "text": "Why is the small intestine in herbivores longer than in carnivores?",
        "answer": "cellulose takes longer to digest",
        "explanation": "Grass is cellulose-rich; longer intestine gives more time for digestion of cellulose.",
        "keywords": ["cellulose", "longer", "digest", "fibre", "fiber"],
    },
    {
        "id": "q-s-life-3",
        "topic_id": "s-life",
        "subject_id": "science",
        "source": "pyq",
        "year": 2023,
        "difficulty": 2,
        "probability": 0.88,
        "marks": 3,
        "type": "short",
        "text": "Name the respiratory pigment in human blood and the organ where oxygenated and deoxygenated blood is separated.",
        "answer": "haemoglobin; heart (four-chambered)",
        "explanation": "Haemoglobin carries O₂. Four-chambered heart keeps oxygenated and deoxygenated blood separate.",
        "keywords": ["haemoglobin", "hemoglobin", "heart"],
    },
    # Science — Electricity
    {
        "id": "q-s-elec-1",
        "topic_id": "s-elec",
        "subject_id": "science",
        "source": "pyq",
        "year": 2024,
        "difficulty": 1,
        "probability": 0.95,
        "marks": 2,
        "type": "mcq",
        "text": "The SI unit of electric current is",
        "options": ["volt", "ohm", "ampere", "watt"],
        "answer": "ampere",
        "explanation": "Current is measured in ampere (A).",
    },
    {
        "id": "q-s-elec-2",
        "topic_id": "s-elec",
        "subject_id": "science",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.92,
        "marks": 3,
        "type": "short",
        "text": "Two resistors 4 Ω and 6 Ω are connected in parallel across a 6 V battery. Find the current drawn from the battery.",
        "answer": "2.5 A",
        "explanation": "1/Rp = 1/4 + 1/6 = 5/12 → Rp = 2.4 Ω. I = V/R = 6/2.4 = 2.5 A.",
        "keywords": ["2.5"],
    },
    {
        "id": "q-s-elec-3",
        "topic_id": "s-elec",
        "subject_id": "science",
        "source": "model",
        "difficulty": 3,
        "probability": 0.80,
        "marks": 4,
        "type": "short",
        "text": "State Joule's law of heating. An electric iron of 1000 W is used for 2 hours. Calculate energy consumed in commercial units.",
        "answer": "2 kWh",
        "explanation": "H = I²Rt. Energy = 1000 W × 2 h = 2 kWh (2 units).",
        "keywords": ["2", "kwh", "unit", "i2rt"],
    },
    # Science — Light
    {
        "id": "q-s-light-1",
        "topic_id": "s-light",
        "subject_id": "science",
        "source": "pyq",
        "year": 2023,
        "difficulty": 2,
        "probability": 0.94,
        "marks": 3,
        "type": "mcq",
        "text": "A concave mirror produces a real, inverted, same-size image. The object is at",
        "options": ["focus", "centre of curvature", "infinity", "between F and P"],
        "answer": "centre of curvature",
        "explanation": "Object at C → image at C, real, inverted, same size.",
    },
    {
        "id": "q-s-light-2",
        "topic_id": "s-light",
        "subject_id": "science",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.88,
        "marks": 3,
        "type": "short",
        "text": "The power of a lens is +2 D. Find its focal length and state whether it is convex or concave.",
        "answer": "0.5 m convex",
        "explanation": "f = 1/P = 0.5 m. Positive power → converging (convex) lens.",
        "keywords": ["0.5", "50 cm", "convex", "converging"],
    },
    {
        "id": "q-s-carbon-1",
        "topic_id": "s-carbon",
        "subject_id": "science",
        "source": "pyq",
        "year": 2024,
        "difficulty": 1,
        "probability": 0.92,
        "marks": 2,
        "type": "mcq",
        "text": "The functional group present in ethanol is",
        "options": ["—CHO", "—COOH", "—OH", "—CO—"],
        "answer": "—OH",
        "explanation": "Ethanol is an alcohol; functional group is hydroxyl (—OH).",
    },
    {
        "id": "q-s-acids-1",
        "topic_id": "s-acids",
        "subject_id": "science",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.90,
        "marks": 3,
        "type": "short",
        "text": "Why does dry HCl gas not change the colour of dry litmus paper?",
        "answer": "no H+ ions without water",
        "explanation": "Acids produce H⁺ only in aqueous solution. Dry HCl has no H⁺ to affect litmus.",
        "keywords": ["hydrogen", "h+", "ion", "water", "aqueous"],
    },
    {
        "id": "q-s-heredity-1",
        "topic_id": "s-heredity",
        "subject_id": "science",
        "source": "pyq",
        "year": 2022,
        "difficulty": 2,
        "probability": 0.84,
        "marks": 3,
        "type": "short",
        "text": "A Mendelian cross of TT × tt for tall/dwarf plants: what is the genotype ratio in F2?",
        "answer": "1:2:1",
        "explanation": "F1 all Tt. F2: TT : Tt : tt = 1 : 2 : 1.",
        "keywords": ["1:2:1", "1 : 2 : 1"],
    },
    {
        "id": "q-s-chemrxn-1",
        "topic_id": "s-chemrxn",
        "subject_id": "science",
        "source": "ncert",
        "difficulty": 1,
        "probability": 0.88,
        "marks": 2,
        "type": "mcq",
        "text": "Fe + CuSO₄ → FeSO₄ + Cu is an example of",
        "options": ["combination", "decomposition", "displacement", "double displacement"],
        "answer": "displacement",
        "explanation": "Iron displaces copper from copper sulphate.",
    },
    # SST
    {
        "id": "q-h-nation-1",
        "topic_id": "h-nation-in",
        "subject_id": "sst",
        "source": "pyq",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.96,
        "marks": 3,
        "type": "short",
        "text": "Why did Gandhiji withdraw the Non-Cooperation Movement?",
        "answer": "Chauri Chaura violence",
        "explanation": "After the Chauri Chaura incident (1922) turned violent, Gandhi withdrew the movement.",
        "keywords": ["chauri", "chaura", "violence", "1922"],
    },
    {
        "id": "q-h-nation-2",
        "topic_id": "h-nation-in",
        "subject_id": "sst",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.90,
        "marks": 3,
        "type": "mcq",
        "text": "The resolution of Purna Swaraj was adopted at which Congress session?",
        "options": ["Lahore 1929", "Nagpur 1920", "Karachi 1931", "Bombay 1915"],
        "answer": "Lahore 1929",
        "explanation": "Lahore session, December 1929, under Jawaharlal Nehru declared Purna Swaraj.",
    },
    {
        "id": "q-p-power-1",
        "topic_id": "p-power",
        "subject_id": "sst",
        "source": "pyq",
        "year": 2023,
        "difficulty": 1,
        "probability": 0.90,
        "marks": 2,
        "type": "mcq",
        "text": "Power sharing is good because it",
        "options": ["reduces conflict", "increases conflict", "weakens democracy", "concentrates power"],
        "answer": "reduces conflict",
        "explanation": "Prudential reason: power sharing reduces the possibility of social conflict.",
    },
    {
        "id": "q-p-fed-1",
        "topic_id": "p-fed",
        "subject_id": "sst",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.86,
        "marks": 3,
        "type": "short",
        "text": "State two features that make India a federal country.",
        "answer": "written constitution; two/three tiers of government",
        "explanation": "India has a written constitution, dual/three-tier government, and division of powers (Union/State/Concurrent lists).",
        "keywords": ["constitution", "union", "state", "list", "tiers", "independent judiciary"],
    },
    {
        "id": "q-e-dev-1",
        "topic_id": "e-dev",
        "subject_id": "sst",
        "source": "pyq",
        "year": 2024,
        "difficulty": 2,
        "probability": 0.88,
        "marks": 3,
        "type": "short",
        "text": "Why is average income not a complete measure of development of a country?",
        "answer": "hides inequality and non-income aspects",
        "explanation": "Average income hides disparities; development also includes health, education, equality, sustainability.",
        "keywords": ["inequality", "average", "health", "education", "hdi"],
    },
    {
        "id": "q-e-sectors-1",
        "topic_id": "e-sectors",
        "subject_id": "sst",
        "source": "ncert",
        "difficulty": 1,
        "probability": 0.90,
        "marks": 2,
        "type": "mcq",
        "text": "Which sector includes agriculture, forestry and fishing?",
        "options": ["primary", "secondary", "tertiary", "quaternary"],
        "answer": "primary",
        "explanation": "Primary sector extracts/produces natural products.",
    },
    {
        "id": "q-e-money-1",
        "topic_id": "e-money",
        "subject_id": "sst",
        "source": "model",
        "difficulty": 2,
        "probability": 0.84,
        "marks": 3,
        "type": "short",
        "text": "Why do banks ask for collateral while lending?",
        "answer": "security against default",
        "explanation": "Collateral is an asset used as security so the bank can recover the loan if the borrower defaults.",
        "keywords": ["collateral", "security", "default", "asset"],
    },
    {
        "id": "q-g-agri-1",
        "topic_id": "g-agri",
        "subject_id": "sst",
        "source": "pyq",
        "year": 2023,
        "difficulty": 1,
        "probability": 0.80,
        "marks": 2,
        "type": "mcq",
        "text": "Which of the following is a rabi crop?",
        "options": ["paddy", "maize", "wheat", "cotton"],
        "answer": "wheat",
        "explanation": "Wheat is sown in winter (rabi) and harvested in spring.",
    },
    {
        "id": "q-g-res-1",
        "topic_id": "g-res",
        "subject_id": "sst",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.82,
        "marks": 3,
        "type": "short",
        "text": "What is resource planning? Why is it essential in India?",
        "answer": "balanced utilisation because resources are unevenly distributed",
        "explanation": "Resource planning is judicious use of resources. India has unequal distribution and overuse in some regions.",
        "keywords": ["planning", "uneven", "conservation", "judicious"],
    },
    {
        "id": "q-m-poly-1",
        "topic_id": "m-poly",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 1,
        "probability": 0.80,
        "marks": 2,
        "type": "mcq",
        "text": "If one zero of p(x) = x² − 3x + k is 1, then k is",
        "options": ["2", "3", "1", "4"],
        "answer": "2",
        "explanation": "p(1) = 0 → 1 − 3 + k = 0 → k = 2.",
    },
    {
        "id": "q-m-real-1",
        "topic_id": "m-real",
        "subject_id": "maths",
        "source": "pyq",
        "year": 2022,
        "difficulty": 2,
        "probability": 0.85,
        "marks": 3,
        "type": "short",
        "text": "Use Euclid's algorithm to find HCF of 135 and 225.",
        "answer": "45",
        "explanation": "225 = 135×1 + 90; 135 = 90×1 + 45; 90 = 45×2 + 0. HCF = 45.",
        "keywords": ["45"],
    },
    {
        "id": "q-s-control-1",
        "topic_id": "s-control",
        "subject_id": "science",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.80,
        "marks": 3,
        "type": "short",
        "text": "Name the hormone that regulates blood sugar and the gland that secretes it.",
        "answer": "insulin; pancreas",
        "explanation": "Insulin from the pancreas (islets of Langerhans) lowers blood glucose.",
        "keywords": ["insulin", "pancreas"],
    },
    {
        "id": "q-s-mag-1",
        "topic_id": "s-mag",
        "subject_id": "science",
        "source": "pyq",
        "year": 2023,
        "difficulty": 2,
        "probability": 0.80,
        "marks": 3,
        "type": "mcq",
        "text": "The device that converts electrical energy to mechanical energy is",
        "options": ["generator", "galvanometer", "electric motor", "ammeter"],
        "answer": "electric motor",
        "explanation": "A motor uses magnetic effect of current to produce motion.",
    },
    {
        "id": "q-h-print-1",
        "topic_id": "h-print",
        "subject_id": "sst",
        "source": "model",
        "difficulty": 1,
        "probability": 0.55,
        "marks": 2,
        "type": "mcq",
        "text": "Gutenberg developed the first printing press in",
        "options": ["England", "France", "Germany", "Italy"],
        "answer": "Germany",
        "explanation": "Johannes Gutenberg, Mainz, Germany, mid-15th century.",
    },
    {
        "id": "q-e-consumer-1",
        "topic_id": "e-consumer",
        "subject_id": "sst",
        "source": "model",
        "difficulty": 1,
        "probability": 0.50,
        "marks": 2,
        "type": "mcq",
        "text": "COPRA was enacted in",
        "options": ["1986", "1991", "2005", "1950"],
        "answer": "1986",
        "explanation": "Consumer Protection Act, 1986 (later replaced/updated in 2019).",
    },
    {
        "id": "q-s-env-1",
        "topic_id": "s-env",
        "subject_id": "science",
        "source": "ncert",
        "difficulty": 1,
        "probability": 0.70,
        "marks": 2,
        "type": "mcq",
        "text": "Which of the following is a biodegradable waste?",
        "options": ["plastic bag", "vegetable peels", "glass", "aluminium foil"],
        "answer": "vegetable peels",
        "explanation": "Organic kitchen waste is broken down by microorganisms.",
    },
    {
        "id": "q-s-repro-1",
        "topic_id": "s-repro",
        "subject_id": "science",
        "source": "pyq",
        "year": 2023,
        "difficulty": 2,
        "probability": 0.86,
        "marks": 3,
        "type": "short",
        "text": "What is the role of the placenta in human reproduction?",
        "answer": "exchange of nutrients and waste between mother and foetus",
        "explanation": "Placenta is the embryo's organ for nutrition, respiration and excretion via the mother's blood, without mixing blood.",
        "keywords": ["nutrient", "oxygen", "waste", "embryo", "foetus", "fetus", "exchange"],
    },
    {
        "id": "q-m-areas-1",
        "topic_id": "m-areas",
        "subject_id": "maths",
        "source": "ncert",
        "difficulty": 2,
        "probability": 0.72,
        "marks": 3,
        "type": "short",
        "text": "Find the area of a sector of angle 60° of a circle with radius 14 cm (π = 22/7).",
        "answer": "102.67 cm²",
        "explanation": "Area = (θ/360)πr² = (60/360)×(22/7)×196 = 154/3 ≈ 102.67 cm².",
        "keywords": ["102", "154/3", "103"],
    },
]


def questions_for_topic(topic_id: str) -> list[dict]:
    return [q for q in QUESTIONS if q["topic_id"] == topic_id]


def question_by_id(question_id: str) -> dict:
    return next(q for q in QUESTIONS if q["id"] == question_id)
