"""More original INI-CET recall MCQs. Facts are standard; wording is not copied from any bank."""

from __future__ import annotations


def Q(qid, topic, subject, text, options, answer, explanation, difficulty=2, probability=0.84):
    return {
        "id": qid,
        "topic_id": topic,
        "subject_id": subject,
        "source": "recall",
        "year": 2025,
        "difficulty": difficulty,
        "probability": probability,
        "marks": 1,
        "type": "mcq",
        "text": text,
        "options": options,
        "answer": answer,
        "explanation": explanation,
    }


EXTRA = [
    Q("q-a-upper-3", "a-upper", "anatomy", "Saturday night palsy typically injures:", ["Radial nerve", "Ulnar nerve", "Median nerve", "Musculocutaneous nerve"], "Radial nerve", "Compression in the spiral groove."),
    Q("q-a-upper-4", "a-upper", "anatomy", "Anatomical snuff box tenderness after a fall on the hand suggests fracture of:", ["Scaphoid", "Lunate", "Hamate", "Pisiform"], "Scaphoid", "Floor of the snuff box is scaphoid.", 3),
    Q("q-a-upper-5", "a-upper", "anatomy", "Clawing of 4th and 5th fingers points to:", ["Ulnar nerve", "Median nerve", "Radial nerve", "Axillary nerve"], "Ulnar nerve", "Ulnar innervates medial two lumbricals and interossei."),
    Q("q-a-upper-6", "a-upper", "anatomy", "Which rotator cuff muscle inserts on the lesser tubercle?", ["Subscapularis", "Supraspinatus", "Infraspinatus", "Teres minor"], "Subscapularis", "The other three insert on the greater tubercle.", 3),
    Q("q-a-lower-3", "a-lower", "anatomy", "Positive Trendelenburg sign means weakness of:", ["Gluteus medius (superior gluteal nerve)", "Gluteus maximus (inferior gluteal)", "Iliopsoas", "Adductor magnus"], "Gluteus medius (superior gluteal nerve)", "Pelvis drops on the unsupported side."),
    Q("q-a-lower-4", "a-lower", "anatomy", "Unhappy triad of the knee classically includes ACL, MCL and:", ["Medial meniscus", "Lateral meniscus", "PCL", "LCL"], "Medial meniscus", "Valgus plus rotation injury."),
    Q("q-a-lower-5", "a-lower", "anatomy", "Loss of dorsiflexion and eversion after a fibular neck fracture:", ["Common peroneal nerve", "Tibial nerve", "Saphenous nerve", "Femoral nerve"], "Common peroneal nerve", "Winds around the neck of fibula."),
    Q("q-a-lower-6", "a-lower", "anatomy", "Femoral triangle base is formed by:", ["Inguinal ligament", "Sartorius", "Adductor longus", "Pectineus"], "Inguinal ligament", "Sartorius lateral, adductor longus medial."),
    Q("q-a-thorax-3", "a-thorax", "anatomy", "SA node is usually supplied by:", ["Right coronary artery", "Circumflex only", "LAD only", "Posterior descending only"], "Right coronary artery", "About 60% RCA; rest circumflex.", 3),
    Q("q-a-thorax-4", "a-thorax", "anatomy", "Azygos vein drains into:", ["SVC", "IVC", "Portal vein", "Coronary sinus"], "SVC", "Arches over the right lung root."),
    Q("q-a-thorax-5", "a-thorax", "anatomy", "Left recurrent laryngeal nerve hooks around:", ["Arch of aorta", "Right subclavian", "Pulmonary trunk", "Ligamentum teres"], "Arch of aorta", "Right recurrent hooks around right subclavian."),
    Q("q-a-thorax-6", "a-thorax", "anatomy", "Typical ribs are:", ["3 to 9", "1 and 2 only", "11 and 12", "All 12"], "3 to 9", "1,2,10,11,12 are atypical."),
    Q("q-p-general-3", "p-general", "physiology", "Typical neuronal resting membrane potential is about:", ["-70 mV", "+40 mV", "0 mV", "+90 mV"], "-70 mV", "K+ leak dominates RMP."),
    Q("q-p-general-4", "p-general", "physiology", "Saltatory conduction occurs in:", ["Myelinated axons", "Unmyelinated C fibres only", "Smooth muscle", "Gap junctions of heart only"], "Myelinated axons", "Action potential jumps node to node."),
    Q("q-p-general-5", "p-general", "physiology", "Smooth muscle contraction uses:", ["Calmodulin", "Troponin C as in skeletal", "Nebulin", "Titin as the Ca2+ sensor"], "Calmodulin", "MLCK pathway; no troponin."),
    Q("q-p-general-6", "p-general", "physiology", "Nernst potential for K+ is nearest:", ["-90 mV", "+60 mV", "-30 mV", "+90 mV"], "-90 mV", "Na+ Nernst is about +60 mV."),
    Q("q-a-head-3", "a-head", "anatomy", "Facial nerve exits the skull via:", ["Stylomastoid foramen", "Foramen ovale", "Jugular foramen", "Foramen rotundum"], "Stylomastoid foramen", "Then through parotid."),
    Q("q-a-head-4", "a-head", "anatomy", "Which is NOT in the cavernous sinus wall/contents?", ["Mandibular nerve (V3)", "Abducens", "Oculomotor", "Trochlear"], "Mandibular nerve (V3)", "V1 and V2 yes; V3 exits ovale.", 3),
    Q("q-a-head-5", "a-head", "anatomy", "Parotid duct opens opposite:", ["Upper 2nd molar", "Lower 2nd molar", "Upper canine", "Lower incisors"], "Upper 2nd molar", "Stensen duct."),
    Q("q-a-head-6", "a-head", "anatomy", "Ansa cervicalis is from:", ["C1-C3", "C5-C6", "CN XI only", "CN X only"], "C1-C3", "Infrahyoid motor."),
    Q("q-a-neuro-3", "a-neuro", "anatomy", "Medial medullary syndrome vessel:", ["Anterior spinal artery", "PICA", "AICA", "SCA"], "Anterior spinal artery", "Pyramid, medial lemniscus, XII."),
    Q("q-a-neuro-4", "a-neuro", "anatomy", "Which artery is NOT a Circle of Willis vessel?", ["Middle cerebral artery", "Anterior communicating", "Posterior communicating", "Anterior cerebral"], "Middle cerebral artery", "MCA is a continuation of ICA, not a circle segment.", 3),
    Q("q-a-neuro-5", "a-neuro", "anatomy", "Broca area is in:", ["Inferior frontal gyrus", "Superior temporal gyrus", "Occipital pole", "Angular gyrus"], "Inferior frontal gyrus", "Dominant hemisphere motor speech."),
    Q("q-a-neuro-6", "a-neuro", "anatomy", "Lateral geniculate nucleus is for:", ["Vision", "Hearing", "Smell", "Taste"], "Vision", "Medial geniculate is auditory."),
    Q("q-p-cvs-3", "p-cvs", "physiology", "Normal PR interval is:", ["0.12-0.20 s", "0.04-0.08 s", "0.36-0.44 s", ">0.30 s always"], "0.12-0.20 s", "Longer = first-degree block."),
    Q("q-p-cvs-4", "p-cvs", "physiology", "Physiological splitting of S2 is wider in:", ["Inspiration", "Expiration", "Valsalva strain only", "Standing only"], "Inspiration", "Delayed P2."),
    Q("q-p-cvs-5", "p-cvs", "physiology", "Stroke volume equals:", ["EDV - ESV", "EDV + ESV", "CO / MAP", "HR x TPR"], "EDV - ESV", "Ejection fraction is SV/EDV."),
    Q("q-p-cvs-6", "p-cvs", "physiology", "Bainbridge reflex: atrial stretch causes:", ["Increased heart rate", "Asystole", "Pure vasoconstriction", "ADH release only"], "Increased heart rate", "Opposite of baroreceptor bradycardia."),
    Q("q-p-resp-3", "p-resp", "physiology", "Anatomic dead space is about:", ["150 ml", "15 ml", "1500 ml", "5 ml"], "150 ml", "Conducting airways."),
    Q("q-p-resp-4", "p-resp", "physiology", "Chloride shift (Hamburger) moves Cl- into RBCs in exchange for:", ["HCO3-", "Na+", "K+", "H+"], "HCO3-", "CO2 transport as bicarbonate."),
    Q("q-p-resp-5", "p-resp", "physiology", "FEV1/FVC is typically reduced in:", ["Obstructive disease", "Restrictive disease only", "Normal lungs only", "Anaemia"], "Obstructive disease", "Restrictive often has normal or high ratio."),
    Q("q-p-resp-6", "p-resp", "physiology", "Hering-Breuer inflation reflex afferents travel in:", ["Vagus", "Phrenic", "Sympathetic chain", "Glossopharyngeal only"], "Vagus", "Stretch receptors in lung."),
    Q("q-b-metab-3", "b-metab", "biochem", "Rate-limiting enzyme of glycolysis:", ["PFK-1", "Hexokinase always only", "Pyruvate carboxylase", "Glucose-6-phosphatase"], "PFK-1", "Also hexokinase/glucokinase and pyruvate kinase are regulated."),
    Q("q-b-metab-4", "b-metab", "biochem", "Urea cycle occurs mainly in:", ["Liver", "Muscle", "Kidney medulla only", "Brain astrocytes only"], "Liver", "CPS-I in mitochondria."),
    Q("q-b-metab-5", "b-metab", "biochem", "HMP shunt's main product for biosynthesis is:", ["NADPH", "ATP only", "Urea", "Creatine"], "NADPH", "Also ribose-5-phosphate."),
    Q("q-b-metab-6", "b-metab", "biochem", "Liver cannot use ketone bodies because it lacks:", ["Thiophorase (SCOT)", "HMG-CoA synthase", "Carnitine", "Citrate synthase"], "Thiophorase (SCOT)", "Liver produces ketones for other tissues.", 3),
    Q("q-b-clinical-3", "b-clinical", "biochem", "More liver-specific transaminase:", ["ALT", "CK-MB", "Amylase", "ACP"], "ALT", "AST also in muscle/RBC."),
    Q("q-b-clinical-4", "b-clinical", "biochem", "Vitamin B12 deficiency causes megaloblastic anaemia plus:", ["Subacute combined degeneration", "Night blindness", "Scurvy", "Beriberi only always"], "Subacute combined degeneration", "Folate megaloblastic without the neuropathy."),
    Q("q-b-clinical-5", "b-clinical", "biochem", "Vitamin K dependent factors:", ["II, VII, IX, X", "VIII, IX, XI, XII", "I, V, VIII, XIII", "III, IV, VI"], "II, VII, IX, X", "Also proteins C and S."),
    Q("q-b-clinical-6", "b-clinical", "biochem", "High anion gap metabolic acidosis example:", ["DKA", "Diarrhoea (normal gap)", "RTA type 2", "Acetazolamide only"], "DKA", "MUDPILES / GOLDMARK."),
    Q("q-ph-general-3", "ph-general", "pharma", "Classic zero-order elimination at therapeutic doses:", ["Phenytoin / ethanol", "Gentamicin always", "Penicillin V always", "Insulin SC always"], "Phenytoin / ethanol", "Saturable metabolism."),
    Q("q-ph-general-4", "ph-general", "pharma", "Strong CYP3A4 inducer:", ["Rifampicin", "Ketoconazole", "Cimetidine", "Grapefruit juice"], "Rifampicin", "Ketoconazole/cimetidine/grapefruit inhibit."),
    Q("q-ph-general-5", "ph-general", "pharma", "Therapeutic index is:", ["TD50 / ED50", "ED50 / TD50", "Tmax / Cmax", "t1/2 / Vd"], "TD50 / ED50", "Wider is safer."),
    Q("q-ph-general-6", "ph-general", "pharma", "Very high Vd suggests the drug is:", ["Highly tissue-bound / lipophilic", "Confined to plasma", "Not absorbed", "Only excreted unchanged always"], "Highly tissue-bound / lipophilic", "Plasma concentration looks low."),
    Q("q-ph-ans-3", "ph-ans", "pharma", "Atropine is dangerous in:", ["Narrow-angle glaucoma", "Bradycardia from vagal tone", "Organophosphate poisoning", "Uveitis for cycloplegia"], "Narrow-angle glaucoma", "Mydriasis can close the angle."),
    Q("q-ph-ans-4", "ph-ans", "pharma", "Cholinesterase inhibitor that crosses BBB:", ["Physostigmine", "Neostigmine", "Pyridostigmine", "Edrophonium"], "Physostigmine", "Tertiary amine; used in atropine overdose."),
    Q("q-ph-ans-5", "ph-ans", "pharma", "Depolarizing neuromuscular blocker:", ["Succinylcholine", "Atracurium", "Vecuronium", "Rocuronium"], "Succinylcholine", "The rest are non-depolarizing."),
    Q("q-ph-ans-6", "ph-ans", "pharma", "Non-selective beta blocker to avoid in asthma:", ["Propranolol", "Atenolol preferred over it", "Salbutamol", "Ipratropium"], "Propranolol", "Blocks beta-2 bronchodilation."),
    Q("q-ph-cvsab-3", "ph-cvsab", "pharma", "ACE inhibitor cough is due to:", ["Bradykinin", "Renin excess only", "Hyperkalaemia", "Hyponatraemia"], "Bradykinin", "Switch to ARB often."),
    Q("q-ph-cvsab-4", "ph-cvsab", "pharma", "Spironolactone adverse effect:", ["Gynaecomastia", "Ototoxicity like loop", "Cough like ACEI always", "Gingival hyperplasia"], "Gynaecomastia", "Anti-androgen; also hyperkalaemia."),
    Q("q-ph-cvsab-5", "ph-cvsab", "pharma", "Red man syndrome is with:", ["Vancomycin rapid infusion", "Gentamicin", "Ciprofloxacin", "Metronidazole"], "Vancomycin rapid infusion", "Slow the infusion; not true IgE always."),
    Q("q-ph-cvsab-6", "ph-cvsab", "pharma", "Isoniazid neuropathy is prevented by:", ["Pyridoxine (B6)", "B12", "Folate", "Vitamin C"], "Pyridoxine (B6)", "INH increases B6 excretion."),
    Q("q-pa-general-3", "pa-general", "pathology", "Caseous necrosis is typical of:", ["TB", "Abscess only", "Infarct of heart", "Fat necrosis of pancreas only"], "TB", "Cheese-like; granuloma."),
    Q("q-pa-general-4", "pa-general", "pathology", "Apoptosis executioner enzymes are:", ["Caspases", "Lysozyme", "Pepsin", "Amylase"], "Caspases", "Programmed cell death."),
    Q("q-pa-general-5", "pa-general", "pathology", "Metaplasia is:", ["Reversible change of one adult cell type to another", "Always cancer", "Irreversible DNA mutation", "Cell swelling only"], "Reversible change of one adult cell type to another", "Barrett is an example."),
    Q("q-pa-general-6", "pa-general", "pathology", "Early granulation tissue collagen is mainly:", ["Type III", "Type I only", "Type II", "Type IV only"], "Type III", "Later remodeled to type I."),
    Q("q-pa-hema-3", "pa-hema", "pathology", "ITP typically shows:", ["Isolated thrombocytopenia", "Pancytopenia always", "High PT/aPTT first", "Schistocytes always"], "Isolated thrombocytopenia", "Anti-platelet antibodies."),
    Q("q-pa-hema-4", "pa-hema", "pathology", "CML defining lesion:", ["t(9;22) BCR-ABL", "t(15;17)", "t(8;14)", "JAK2 V617F always"], "t(9;22) BCR-ABL", "Philadelphia chromosome."),
    Q("q-pa-hema-5", "pa-hema", "pathology", "Heinz bodies suggest:", ["G6PD deficiency", "Iron deficiency", "B12 deficiency", "Aplastic anaemia"], "G6PD deficiency", "Oxidative haemolysis."),
    Q("q-pa-hema-6", "pa-hema", "pathology", "Haemophilia A is deficiency of:", ["Factor VIII", "Factor IX", "Factor VII", "vWF only always"], "Factor VIII", "IX is haemophilia B."),
    Q("q-pa-systemic-3", "pa-systemic", "pathology", "Crescents in glomeruli mean:", ["RPGN", "Minimal change", "Membranous only", "Diabetic Kimmelstiel-Wilson only"], "RPGN", "Rapidly progressive GN."),
    Q("q-pa-systemic-4", "pa-systemic", "pathology", "Aschoff bodies are seen in:", ["Rheumatic carditis", "Infective endocarditis vegetations only", "Libman-Sacks", "Amyloid"], "Rheumatic carditis", "Anitschkow cells."),
    Q("q-pa-systemic-5", "pa-systemic", "pathology", "Mallory hyaline (bodies) classic in:", ["Alcoholic hepatitis", "Viral hepatitis A only", "Wilson always", "Haemochromatosis only"], "Alcoholic hepatitis", "Intermediate filaments."),
    Q("q-pa-systemic-6", "pa-systemic", "pathology", "Ghon complex is:", ["Primary TB (Ghon focus + hilar node)", "Miliary TB only", "Reactivation apex only", "NTM always"], "Primary TB (Ghon focus + hilar node)", "Lower lobe or mid zone plus node."),
    Q("q-mi-bacteria-3", "mi-bacteria", "micro", "Autoclave standard:", ["121 C, 15 min, 15 psi", "100 C, 5 min", "160 C dry 1 min", "37 C overnight"], "121 C, 15 min, 15 psi", "Steam under pressure."),
    Q("q-mi-bacteria-4", "mi-bacteria", "micro", "Pseudomembranous colitis toxin organism:", ["C. difficile", "S. aureus food poisoning only", "V. cholerae", "H. pylori"], "C. difficile", "Toxin A/B; after antibiotics."),
    Q("q-mi-bacteria-5", "mi-bacteria", "micro", "N. meningitidis ferments:", ["Glucose and maltose", "Glucose only", "Lactose", "None"], "Glucose and maltose", "N. gonorrhoeae glucose only.", 3),
    Q("q-mi-bacteria-6", "mi-bacteria", "micro", "GAS (S. pyogenes) is typically:", ["Catalase negative, beta-haemolytic", "Catalase positive", "Acid-fast", "Spore-forming"], "Catalase negative, beta-haemolytic", "Staph is catalase positive."),
    Q("q-mi-virology-3", "mi-virology", "micro", "HBV genome is:", ["DNA", "Positive-sense RNA only", "Negative RNA only", "dsRNA like rota"], "DNA", "Hepadnavirus; RT still involved."),
    Q("q-mi-virology-4", "mi-virology", "micro", "Pandemic influenza jumps by:", ["Antigenic shift", "Antigenic drift only", "Latency in DRG", "Plasmid conjugation"], "Antigenic shift", "Reassortment; drift is seasonal."),
    Q("q-mi-virology-5", "mi-virology", "micro", "Germ tube test is for:", ["Candida albicans", "Crypto neoformans", "Aspergillus", "Mucor"], "Candida albicans", "Serum 2 hours."),
    Q("q-mi-virology-6", "mi-virology", "micro", "E. histolytica intestinal ulcers are classically:", ["Flask-shaped", "Linear like UC always", "Transmural skip like Crohn always", "Pseudomembrane like C. diff"], "Flask-shaped", "Invasive amoebiasis."),
    Q("q-me-cardio-3", "me-cardio", "medicine", "STEMI first priority if PCI available promptly:", ["Reperfusion", "Oral iron", "Beta blocker only and wait", "Digoxin loading"], "Reperfusion", "Door to balloon / fibrinolysis rules."),
    Q("q-me-cardio-4", "me-cardio", "medicine", "AF ECG:", ["Irregularly irregular, no P waves", "Regular sawtooth", "Prolonged PR only", "Delta wave"], "Irregularly irregular, no P waves", "Flutter is sawtooth."),
    Q("q-me-cardio-5", "me-cardio", "medicine", "Aortic stenosis murmur:", ["Ejection systolic to carotids", "Pansystolic to axilla", "Early diastolic at left sternal", "Mid-diastolic with opening snap"], "Ejection systolic to carotids", "MR goes to axilla."),
    Q("q-me-cardio-6", "me-cardio", "medicine", "Beck triad (tamponade):", ["Hypotension, raised JVP, muffled hearts", "Hypertension, bradycardia, irregular breathing", "Fever, new murmur, splinters", "Chest pain, pulsus paradoxus only always listed as three"], "Hypotension, raised JVP, muffled hearts", "Pulsus paradoxus often present too."),
    Q("q-me-endo-3", "me-endo", "medicine", "Graves disease antibody:", ["TSH receptor stimulating", "Anti-TPO only", "Anti-insulin", "Anti-GAD only"], "TSH receptor stimulating", "TPO more Hashimoto."),
    Q("q-me-endo-4", "me-endo", "medicine", "Addison disease typically has:", ["Hyponatraemia and hyperpigmentation", "Hypertension and hypokalaemia", "Moon face", "Exophthalmos"], "Hyponatraemia and hyperpigmentation", "High ACTH; salt wasting."),
    Q("q-me-endo-5", "me-endo", "medicine", "DKA vs HHS: ketones are prominent in:", ["DKA", "HHS always more", "Both equally always", "Neither"], "DKA", "HHS has very high glucose, little ketosis."),
    Q("q-me-endo-6", "me-endo", "medicine", "SIADH labs:", ["Hyponatraemia, inappropriately concentrated urine", "Hypernatraemia, dilute urine", "High glucose always", "Low urine Na"], "Hyponatraemia, inappropriately concentrated urine", "Euvolemic hypoNa."),
    Q("q-me-nephro-3", "me-nephro", "medicine", "Pre-renal AKI FeNa is typically:", ["<1%", ">4% always", "Exactly 20%", "Unmeasurable"], "<1%", "Kidneys conserve sodium."),
    Q("q-me-nephro-4", "me-nephro", "medicine", "Nephrotic syndrome includes:", ["Hypoalbuminaemia, oedema, hyperlipidaemia", "Only haematuria", "Always RPGN crescents", "Always low complement"], "Hypoalbuminaemia, oedema, hyperlipidaemia", "Plus heavy proteinuria."),
    Q("q-me-nephro-5", "me-nephro", "medicine", "More specific enzyme for pancreatitis:", ["Lipase", "AST", "ALP", "CK"], "Lipase", "Amylase also rises but less specific."),
    Q("q-me-nephro-6", "me-nephro", "medicine", "Hepatitis A transmission:", ["Faecal-oral", "Needlestick mainly", "Vertical always", "Aerosol like measles"], "Faecal-oral", "No chronic carrier state."),
    Q("q-ps-epi-3", "ps-epi", "psm", "Sensitivity is:", ["True positive rate", "True negative rate", "PPV", "NPV"], "True positive rate", "TP / (TP+FN)."),
    Q("q-ps-epi-4", "ps-epi", "psm", "Case-control studies classically estimate:", ["Odds ratio", "Relative risk directly from incidence", "NNT from RCT only", "Standardised mortality only"], "Odds ratio", "RR needs incidence."),
    Q("q-ps-epi-5", "ps-epi", "psm", "Prevalence vs incidence: prevalence is:", ["Existing cases at a time", "New cases only", "Always smaller than incidence", "Only for death"], "Existing cases at a time", "Incidence is new cases over time."),
    Q("q-ps-epi-6", "ps-epi", "psm", "Confounding is:", ["A third factor associated with exposure and outcome", "Random error only", "Placebo effect", "Loss to follow-up only"], "A third factor associated with exposure and outcome", "Control by matching, restriction, regression."),
    Q("q-ps-programs-3", "ps-programs", "psm", "BCG in the national schedule is given at:", ["Birth", "9 months only", "5 years only", "Never"], "Birth", "Intradermal left arm."),
    Q("q-ps-programs-4", "ps-programs", "psm", "First measles-containing vaccine in NIS is around:", ["9 months", "Birth", "6 weeks", "15 years"], "9 months", "MR; booster later."),
    Q("q-ps-programs-5", "ps-programs", "psm", "RNTCP was renamed:", ["NTEP", "NACP", "NVBDCP", "NPCDCS"], "NTEP", "National TB Elimination Programme."),
    Q("q-ps-programs-6", "ps-programs", "psm", "IMR is deaths under 1 year per:", ["1000 live births", "100 live births", "1000 population", "100000 live births"], "1000 live births", "Standard vital statistic."),
    Q("q-su-general-3", "su-general", "surgery", "Direct inguinal hernia is medial to:", ["Inferior epigastric vessels", "Pubic tubercle", "Femoral vein", "ASIS"], "Inferior epigastric vessels", "Hesselbach triangle."),
    Q("q-su-general-4", "su-general", "surgery", "Courvoisier law: painless palpable gallbladder suggests:", ["Malignant obstruction, not stone", "Always gallstones", "Always pancreatitis", "Always amoebic liver abscess"], "Malignant obstruction, not stone", "Stones usually scar the GB."),
    Q("q-su-general-5", "su-general", "surgery", "Triple assessment of a breast lump is:", ["Clinical + imaging + pathology", "Only mammogram", "Only FNAC", "Only family history"], "Clinical + imaging + pathology", "Age decides mammo vs USG."),
    Q("q-su-general-6", "su-general", "surgery", "Tension pneumothorax immediate step:", ["Needle decompression then chest drain", "CT first", "Bronchoscopy", "Wait for CXR in unstable patient"], "Needle decompression then chest drain", "2nd ICS MCL or 5th ICS MAL."),
    Q("q-su-gi-3", "su-gi", "surgery", "McBurney point is for:", ["Appendix", "Gallbladder", "Spleen", "Kidney"], "Appendix", "1/3 from ASIS to umbilicus."),
    Q("q-su-gi-4", "su-gi", "surgery", "Intussusception stool is classically:", ["Red currant jelly", "Melaena only", "Clay coloured", "Rice water"], "Red currant jelly", "Target sign on USG; infants."),
    Q("q-su-gi-5", "su-gi", "surgery", "Internal haemorrhoids (above dentate) are typically:", ["Painless bleeding", "Very painful thrombosis always", "Always malignant", "Always infected"], "Painless bleeding", "Visceral innervation above dentate."),
    Q("q-su-gi-6", "su-gi", "surgery", "Perforated peptic ulcer CXR:", ["Air under diaphragm", "Cannon ball mets", "Kerley B only", "Normal always"], "Air under diaphragm", "Pneumoperitoneum."),
    Q("q-or-trauma-3", "or-trauma", "ortho", "Colles fracture dinner-fork is:", ["Distal radius, extra-articular typically", "Scaphoid waist", "Clavicle midshaft", "Neck of femur"], "Distal radius, extra-articular typically", "FOOSH in elderly."),
    Q("q-or-trauma-4", "or-trauma", "ortho", "Fat embolism triad after long-bone fracture:", ["Respiratory distress, petechiae, neuro change", "Only fever", "Only local swelling", "Only fat on CXR always"], "Respiratory distress, petechiae, neuro change", "24-72 h later."),
    Q("q-or-trauma-5", "or-trauma", "ortho", "Compartment syndrome treatment:", ["Fasciotomy", "Tight cast continue", "Only elevation forever", "Antibiotics only"], "Fasciotomy", "Pain on passive stretch is early."),
    Q("q-or-trauma-6", "or-trauma", "ortho", "Posterior hip dislocation: limb is:", ["Short, flexed, adducted, internally rotated", "Short, abducted, externally rotated", "Long and internally rotated", "Normal length always"], "Short, flexed, adducted, internally rotated", "Sciatic nerve risk. NOF fracture is ER."),
    Q("q-or-spine-3", "or-spine", "ortho", "L4-L5 disc typically affects root:", ["L5", "L4 only always", "S2", "T12"], "L5", "Posterolateral disc hits the traversing root."),
    Q("q-or-spine-4", "or-spine", "ortho", "Osteoporotic fractures favour:", ["Vertebra, hip, wrist", "Skull vault always", "Phalanges first", "Patella only"], "Vertebra, hip, wrist", "Fragility sites."),
    Q("q-or-spine-5", "or-spine", "ortho", "CTEV (clubfoot) first-line:", ["Ponseti serial casting", "Immediate Ilizarov always", "Only shoes", "Amputation"], "Ponseti serial casting", "Then boots and bar."),
    Q("q-or-spine-6", "or-spine", "ortho", "Osteosarcoma classic site and X-ray:", ["Metaphysis around knee, sunburst / Codman", "Epiphysis giant cell only", "Diaphysis Ewing only always", "Skull osteoma"], "Metaphysis around knee, sunburst / Codman", "Adolescents."),
    Q("q-ob-obs-3", "ob-obs", "obg", "Atonic PPH first mechanical step:", ["Uterine massage + uterotonics", "Hysterectomy first", "Only IV fluids", "Forceps"], "Uterine massage + uterotonics", "Oxytocin, then stepwise."),
    Q("q-ob-obs-4", "ob-obs", "obg", "Eclampsia seizure drug of choice:", ["MgSO4", "Phenytoin first always", "Diazepam only forever", "Mannitol first"], "MgSO4", "Pritchard / Zuspan; also prophylaxis."),
    Q("q-ob-obs-5", "ob-obs", "obg", "Painless third-trimester bleed, high presenting part:", ["Placenta praevia", "Abruption", "Uterine rupture", "Vasa praevia only always"], "Placenta praevia", "Abruption is painful, tense uterus."),
    Q("q-ob-obs-6", "ob-obs", "obg", "Bishop score assesses:", ["Cervix for induction", "Pelvic inlet cm", "Fetal weight only", "AFI only"], "Cervix for induction", "Dilatation, effacement, station, consistency, position."),
    Q("q-ob-gyn-3", "ob-gyn", "obg", "PCOS Rotterdam needs 2 of 3: oligo-ovulation, hyperandrogenism, and:", ["Polycystic ovaries on USG", "Always diabetes", "Always CAH", "Always hypothyroidism"], "Polycystic ovaries on USG", "Exclude other causes."),
    Q("q-ob-gyn-4", "ob-gyn", "obg", "High-risk HPV for cervix:", ["16 and 18", "6 and 11 only", "1 and 2", "EBV"], "16 and 18", "6/11 are warts / low risk."),
    Q("q-ob-gyn-5", "ob-gyn", "obg", "LNG emergency contraception is best within:", ["72 hours", "2 weeks", "Only before intercourse", "6 months"], "72 hours", "Sooner is better; Cu-IUD longer window."),
    Q("q-ob-gyn-6", "ob-gyn", "obg", "Chocolate cyst is:", ["Endometrioma of ovary", "Follicular cyst", "Mucinous cystadenoma", "Abscess always"], "Endometrioma of ovary", "Endometriosis."),
    Q("q-pe-neonatal-3", "pe-neonatal", "peds", "Physiological jaundice typically starts after:", ["24 hours of life", "First 2 hours always", "Day 14 always pathological only", "Never in term babies"], "24 hours of life", "Earlier is pathological until proven otherwise."),
    Q("q-pe-neonatal-4", "pe-neonatal", "peds", "APGAR is recorded at:", ["1 and 5 minutes", "Only at birth second", "Day 1 and 7", "Only if preterm"], "1 and 5 minutes", "Repeat at 10 if still low."),
    Q("q-pe-neonatal-5", "pe-neonatal", "peds", "IM vitamin K at birth prevents:", ["Haemorrhagic disease of newborn", "Rickets", "Scurvy", "Kernicterus from ABO only"], "Haemorrhagic disease of newborn", "Vitamin K dependent factors."),
    Q("q-pe-neonatal-6", "pe-neonatal", "peds", "Hypoglycaemia risk is high in:", ["Infant of diabetic mother / preterm", "Term AGA always", "Only post-term never", "Breastfed exclusively never"], "Infant of diabetic mother / preterm", "Hyperinsulinism in IDM."),
    Q("q-pe-infections-3", "pe-infections", "peds", "Koplik spots are:", ["Measles", "Mumps", "Rubella", "Roseola"], "Measles", "Buccal mucosa before rash."),
    Q("q-pe-infections-4", "pe-infections", "peds", "WHO ORS is used for:", ["Diarrhoea dehydration", "Croup first line", "Seizures", "Anaphylaxis"], "Diarrhoea dehydration", "Low-osmolar ORS."),
    Q("q-pe-infections-5", "pe-infections", "peds", "SAM includes weight-for-height <-3 SD or:", ["Bilateral pitting oedema / MUAC <11.5 cm (6-59 mo)", "Only fever", "Only cough", "BMI 22"], "Bilateral pitting oedema / MUAC <11.5 cm (6-59 mo)", "WHO definitions."),
    Q("q-pe-infections-6", "pe-infections", "peds", "Acute bacterial meningitis empiric in older infant often includes:", ["3rd generation cephalosporin", "Oral amoxicillin only", "Aciclovir only", "Albendazole"], "3rd generation cephalosporin", "Plus amp/gent in neonates; add vanco where resistant pneumococcus."),
    Q("q-eo-ent-3", "eo-ent", "ent_ophth", "Unsafe CSOM with cholesteatoma is often:", ["Attic / posterosuperior retraction", "Central perforation only always safe", "Furuncle of canal", "Otosclerosis"], "Attic / posterosuperior retraction", "Risk of complication."),
    Q("q-eo-ent-4", "eo-ent", "ent_ophth", "Meniere triad:", ["Vertigo, tinnitus, fluctuating hearing", "Only otalgia", "Only anosmia", "Facial palsy only"], "Vertigo, tinnitus, fluctuating hearing", "Endolymphatic hydrops."),
    Q("q-eo-ent-5", "eo-ent", "ent_ophth", "Little's area (Kiesselbach) is for:", ["Anterior epistaxis", "Posterior bleed always", "CSF rhinorrhoea", "Choanal atresia"], "Anterior epistaxis", "Anastomosis on septum."),
    Q("q-eo-ent-6", "eo-ent", "ent_ophth", "Quinsy is:", ["Peritonsillar abscess", "Retropharyngeal in infant only", "Otitis externa", "Sinusitis"], "Peritonsillar abscess", "Hot potato voice, trismus."),
    Q("q-eo-ophth-3", "eo-ophth", "ent_ophth", "Primary open-angle glaucoma is typically:", ["Painless gradual field loss", "Acute red painful eye always", "Sudden complete blackout always", "Only in children"], "Painless gradual field loss", "Angle-closure is acute painful."),
    Q("q-eo-ophth-4", "eo-ophth", "ent_ophth", "Absent red reflex in a child: rule out:", ["Cataract / retinoblastoma", "Simple refractive error only", "Squint only", "Dacryocystitis only"], "Cataract / retinoblastoma", "Leukocoria workup."),
    Q("q-eo-ophth-5", "eo-ophth", "ent_ophth", "Bitot spots are:", ["Vitamin A deficiency", "Vitamin C", "Vitamin D", "Vitamin K"], "Vitamin A deficiency", "Also night blindness, keratomalacia."),
    Q("q-eo-ophth-6", "eo-ophth", "ent_ophth", "Sympathetic ophthalmia affects:", ["The fellow eye after penetrating injury", "Only the injured eye forever", "Eyelids only", "Optic chiasm tumour"], "The fellow eye after penetrating injury", "Bilateral granulomatous uveitis."),
    Q("q-fo-legal-3", "fo-legal", "forensic", "IPC 304A is:", ["Death by rash/negligent act", "Murder", "Dowry death", "Grievous hurt only"], "Death by rash/negligent act", "Medical negligence often discussed here."),
    Q("q-fo-legal-4", "fo-legal", "forensic", "Rigor mortis usually begins around:", ["2-4 hours", "Immediately at 0 min always", "After 3 days only", "Never in tropics"], "2-4 hours", "Nysten's rule; passes in 18-36 h roughly."),
    Q("q-fo-legal-5", "fo-legal", "forensic", "Organophosphate poisoning antidotes:", ["Atropine + pralidoxime", "Naloxone", "Flumazenil", "N-acetylcysteine"], "Atropine + pralidoxime", "Atropine for muscarinic; PAM before ageing."),
    Q("q-fo-legal-6", "fo-legal", "forensic", "Dying declaration is given to:", ["Magistrate preferably; doctor may record", "Only police always invalid", "Only family", "Never admissible"], "Magistrate preferably; doctor may record", "Section 32 Evidence Act."),
    Q("q-fo-psych-3", "fo-psych", "forensic", "Schneider first-rank symptoms are for:", ["Schizophrenia", "Unipolar depression only", "OCD only", "Delirium only"], "Schizophrenia", "Thought echo, voices, passivity, delusional perception."),
    Q("q-fo-psych-4", "fo-psych", "forensic", "First-line for typical major depression:", ["SSRI", "MAOI first always", "ECT first always", "Typical antipsychotic first"], "SSRI", "ECT if severe / psychotic / refusal to eat."),
    Q("q-fo-psych-5", "fo-psych", "forensic", "Delirium vs dementia: delirium is:", ["Acute, fluctuating, impaired attention", "Insidious over years always", "Always irreversible", "Normal consciousness"], "Acute, fluctuating, impaired attention", "Find the medical cause."),
    Q("q-fo-psych-6", "fo-psych", "forensic", "Alcohol withdrawal seizures: treat with:", ["Benzodiazepines", "SSRI", "Lithium", "Methylphenidate"], "Benzodiazepines", "CIWA protocol; thiamine too."),
    Q("q-me-revision-3", "me-revision", "medicine", "CURB-65 is for:", ["Community pneumonia severity", "STEMI", "Stroke", "UTI only"], "Community pneumonia severity", "Confusion, urea, RR, BP, age."),
    Q("q-me-revision-4", "me-revision", "medicine", "Wells score is used in suspected:", ["PE / DVT", "MI only", "Meningitis", "Pancreatitis"], "PE / DVT", "Pre-test probability."),
    Q("q-me-revision-5", "me-revision", "medicine", "Raised JVP is expected in:", ["Right heart failure / tamponade", "Dehydration", "Haemorrhage with empty veins", "Only left-sided S3"], "Right heart failure / tamponade", "Also constriction, PE, SVC obstruction."),
    Q("q-me-revision-6", "me-revision", "medicine", "Clubbing is NOT typical of simple:", ["COPD / chronic bronchitis", "Bronchiectasis", "Lung abscess", "Empyema"], "COPD / chronic bronchitis", "If clubbing in a smoker, think cancer or suppuration."),
    Q("q-ph-revision-3", "ph-revision", "pharma", "Statins inhibit:", ["HMG-CoA reductase", "ACE", "COX-2 only", "Na/K ATPase"], "HMG-CoA reductase", "Myopathy; check interactions with CYP3A4."),
    Q("q-ph-revision-4", "ph-revision", "pharma", "Digoxin toxicity is more likely with:", ["Hypokalaemia", "Hyperkalaemia as the trigger", "Hypermagnesaemia", "High calcium never relevant"], "Hypokalaemia", "Also renal failure and some CYP/P-gp drugs; xanthopsia."),
    Q("q-ph-revision-5", "ph-revision", "pharma", "Allopurinol inhibits:", ["Xanthine oxidase", "COX-1", "MAO-A", "Aromatase"], "Xanthine oxidase", "Azathioprine interaction."),
    Q("q-ph-revision-6", "ph-revision", "pharma", "Anticoagulant preferred in pregnancy:", ["Heparin (LMWH)", "Warfarin throughout", "Rivaroxaban freely", "Dabigatran freely"], "Heparin (LMWH)", "Warfarin teratogenic especially 6-12 weeks."),
]
