"""Extra in-app drills. Original statements; GFG / CSES / CP-Algorithms as after-miss reading."""

from __future__ import annotations

EXTRA_DRILLS: list[dict] = [
    {
        "id": "d-boot-freq",
        "module_id": "bootcamp",
        "title": "Count a letter",
        "type": "code",
        "rating": 800,
        "source": {"title": "GeeksforGeeks - Hashing", "url": "https://www.geeksforgeeks.org/dsa/hashing-data-structure/"},
        "text": "Line 1: a string s of lowercase letters (1 <= |s| <= 200). Line 2: one letter c. Print how many times c appears in s.",
        "sample": {"stdin": "banana\na\n", "stdout": "3\n"},
        "starter": "s = input().strip()\nc = input().strip()\n",
        "tests": [
            {"stdin": "banana\na\n", "stdout": "3\n"},
            {"stdin": "zzz\nz\n", "stdout": "3\n"},
            {"stdin": "abc\nd\n", "stdout": "0\n", "hidden": True},
        ],
        "explanation": "s.count(c), or a loop. Same idea as a frequency map.",
    },
    {
        "id": "d-boot-rev",
        "module_id": "bootcamp",
        "title": "Reverse the whole string",
        "type": "mcq",
        "rating": 800,
        "source": {"title": "GeeksforGeeks - Reverse a string", "url": "https://www.geeksforgeeks.org/dsa/reverse-a-string/"},
        "text": "s = \"ab cd\". What is s[::-1] in Python?",
        "options": ["ba dc", "dc ba", "d c b a", "ab cd"],
        "answer": "dc ba",
        "explanation": "A slice reverse flips the whole string, including the space.",
    },
    {
        "id": "d-boot-sum",
        "module_id": "bootcamp",
        "title": "Sum 1 to n",
        "type": "code",
        "rating": 800,
        "source": {"title": "GeeksforGeeks - Time complexity", "url": "https://www.geeksforgeeks.org/dsa/time-complexity-and-space-complexity/"},
        "text": "Read n (1 <= n <= 10000). Print 1+2+...+n. A formula is O(1); a loop is also accepted.",
        "sample": {"stdin": "5\n", "stdout": "15\n"},
        "starter": "n = int(input())\n",
        "tests": [
            {"stdin": "5\n", "stdout": "15\n"},
            {"stdin": "1\n", "stdout": "1\n"},
            {"stdin": "10\n", "stdout": "55\n", "hidden": True},
        ],
        "explanation": "n*(n+1)//2.",
    },
    {
        "id": "d-impl-unique",
        "module_id": "impl",
        "title": "First unique",
        "type": "code",
        "rating": 900,
        "source": {"title": "GeeksforGeeks - Hashing", "url": "https://www.geeksforgeeks.org/dsa/hashing-data-structure/"},
        "text": "Read a lowercase string s (1 <= |s| <= 200). Print the first character that appears exactly once. If none, print -1.",
        "sample": {"stdin": "abacabad\n", "stdout": "c\n"},
        "starter": "s = input().strip()\n",
        "tests": [
            {"stdin": "abacabad\n", "stdout": "c\n"},
            {"stdin": "aabb\n", "stdout": "-1\n"},
            {"stdin": "xyz\n", "stdout": "x\n", "hidden": True},
        ],
        "explanation": "Count frequencies, then scan s left to right.",
    },
    {
        "id": "d-impl-fizz",
        "module_id": "impl",
        "title": "Three rules",
        "type": "short",
        "rating": 800,
        "source": {"title": "GeeksforGeeks - Loops in Python", "url": "https://www.geeksforgeeks.org/python/loops-in-python/"},
        "text": "For i from 1 to 6 print F if i%3==0, B if i%2==0, else i. If both 2 and 3, print FB. Space-separated.",
        "answer": "1 B F B 5 FB",
        "keywords": ["1 B F B 5 FB"],
        "explanation": "6 is divisible by both 2 and 3, so FB.",
    },
    {
        "id": "d-impl-stack",
        "module_id": "impl",
        "title": "Balanced brackets",
        "type": "mcq",
        "rating": 1000,
        "source": {"title": "GeeksforGeeks - Stack", "url": "https://www.geeksforgeeks.org/dsa/stack-data-structure/"},
        "text": "Using a stack, is \"([]{})\" balanced?",
        "options": ["yes", "no", "only if we ignore ()", "only curly"],
        "answer": "yes",
        "explanation": "Push opens, pop on a matching close. Empty stack at the end.",
    },
    {
        "id": "d-math-mod",
        "module_id": "math",
        "title": "Last digit of a sum",
        "type": "code",
        "rating": 900,
        "source": {"title": "GeeksforGeeks - Modular arithmetic", "url": "https://www.geeksforgeeks.org/dsa/modular-arithmetic/"},
        "text": "Read two integers a b (0 <= a,b <= 10**9). Print (a+b) mod 10.",
        "sample": {"stdin": "19 12\n", "stdout": "1\n"},
        "starter": "a, b = map(int, input().split())\n",
        "tests": [
            {"stdin": "19 12\n", "stdout": "1\n"},
            {"stdin": "0 0\n", "stdout": "0\n"},
            {"stdin": "999 1\n", "stdout": "0\n", "hidden": True},
        ],
        "explanation": "(a + b) % 10.",
    },
    {
        "id": "d-math-prime",
        "module_id": "math",
        "title": "Is 1 prime?",
        "type": "mcq",
        "rating": 800,
        "source": {"title": "GeeksforGeeks - Prime numbers", "url": "https://www.geeksforgeeks.org/dsa/prime-numbers/"},
        "text": "How many primes are in {1, 2, 9, 11}?",
        "options": ["1", "2", "3", "4"],
        "answer": "2",
        "explanation": "2 and 11. 1 is not prime. 9 = 3*3.",
    },
    {
        "id": "d-math-lcm",
        "module_id": "math",
        "title": "LCM from GCD",
        "type": "short",
        "rating": 1000,
        "source": {"title": "GeeksforGeeks - LCM of two numbers", "url": "https://www.geeksforgeeks.org/dsa/program-to-find-lcm-of-two-numbers/"},
        "text": "lcm(a,b) = a*b / gcd(a,b). What is lcm(12, 18)?",
        "answer": "36",
        "keywords": ["36"],
        "explanation": "gcd is 6, so 12*18/6 = 36.",
    },
    {
        "id": "d-greedy-frac",
        "module_id": "greedy",
        "title": "Fractional knapsack pick",
        "type": "mcq",
        "rating": 1200,
        "source": {"title": "GeeksforGeeks - Fractional knapsack", "url": "https://www.geeksforgeeks.org/dsa/fractional-knapsack-problem/"},
        "text": "Fractional knapsack: sort items by:",
        "options": ["weight only", "value only", "value/weight density", "index order"],
        "answer": "value/weight density",
        "explanation": "Take densest first; you may take a fraction of the last item.",
    },
    {
        "id": "d-greedy-interval",
        "module_id": "greedy",
        "title": "Activity pick sort key",
        "type": "mcq",
        "rating": 1200,
        "source": {"title": "GeeksforGeeks - Activity selection", "url": "https://www.geeksforgeeks.org/dsa/activity-selection-problem-greedy-algo-1/"},
        "text": "To pick the maximum number of non-overlapping intervals, sort by:",
        "options": ["start time", "finish time", "length", "start then length"],
        "answer": "finish time",
        "explanation": "Earliest finish, then skip overlaps.",
    },
    {
        "id": "d-greedy-huffman",
        "module_id": "greedy",
        "title": "Huffman idea",
        "type": "short",
        "rating": 1400,
        "source": {"title": "GeeksforGeeks - Huffman coding", "url": "https://www.geeksforgeeks.org/dsa/huffman-coding-greedy-algo-3/"},
        "text": "Huffman always merges the two current trees with:",
        "answer": "smallest frequency",
        "keywords": ["smallest", "least frequent", "minimum"],
        "explanation": "Greedy: combine the two rarest symbols / trees.",
    },
    {
        "id": "d-search-bs",
        "module_id": "search",
        "title": "Binary search predicate",
        "type": "mcq",
        "rating": 1200,
        "source": {"title": "GeeksforGeeks - Binary search", "url": "https://www.geeksforgeeks.org/dsa/binary-search/"},
        "text": "Binary search on the answer needs F(x) = \"x is feasible\" to be:",
        "options": ["random", "monotonic (false then true, or true then false)", "periodic", "always true at x=0"],
        "answer": "monotonic (false then true, or true then false)",
        "explanation": "That is what lets you discard half the range.",
    },
    {
        "id": "d-search-lower",
        "module_id": "search",
        "title": "First true",
        "type": "short",
        "rating": 1100,
        "source": {"title": "GeeksforGeeks - Lower bound", "url": "https://www.geeksforgeeks.org/dsa/implementing-upper-bound-and-lower-bound-in-c/"},
        "text": "Sorted array [1, 3, 3, 7, 9]. Smallest 0-based index i with a[i] >= 3?",
        "answer": "1",
        "keywords": ["1"],
        "explanation": "Lower bound of 3 is the first 3.",
    },
    {
        "id": "d-search-two",
        "module_id": "search",
        "title": "Pair sum",
        "type": "code",
        "rating": 1100,
        "source": {"title": "GeeksforGeeks - Two pointers", "url": "https://www.geeksforgeeks.org/dsa/two-pointers-technique/"},
        "text": "Line 1: n x. Line 2: n distinct integers. Print YES if two different elements sum to x, else NO. n <= 200.",
        "sample": {"stdin": "4 9\n1 4 5 7\n", "stdout": "YES\n"},
        "starter": "n, x = map(int, input().split())\na = list(map(int, input().split()))\n",
        "tests": [
            {"stdin": "4 9\n1 4 5 7\n", "stdout": "YES\n"},
            {"stdin": "3 10\n1 2 3\n", "stdout": "NO\n"},
            {"stdin": "2 3\n1 2\n", "stdout": "YES\n", "hidden": True},
        ],
        "explanation": "Hash set of seen values, or sort plus two pointers.",
    },
    {
        "id": "d-pref-2d",
        "module_id": "prefix",
        "title": "2D prefix inclusion",
        "type": "mcq",
        "rating": 1400,
        "source": {"title": "GeeksforGeeks - Prefix sum", "url": "https://www.geeksforgeeks.org/dsa/prefix-sum-array/"},
        "text": "2D prefix P[r][c] = sum of the rectangle (1,1)..(r,c). Sum of (r1,c1)..(r2,c2) is:",
        "options": [
            "P[r2][c2] only",
            "P[r2][c2] - P[r1-1][c2] - P[r2][c1-1] + P[r1-1][c1-1]",
            "P[r2][c2] - P[r1][c1]",
            "P[r2][c2] + P[r1][c1]",
        ],
        "answer": "P[r2][c2] - P[r1-1][c2] - P[r2][c1-1] + P[r1-1][c1-1]",
        "explanation": "Inclusion-exclusion so the top-left block is not subtracted twice.",
    },
    {
        "id": "d-g1-deg",
        "module_id": "graphs1",
        "title": "Handshaking lemma",
        "type": "short",
        "rating": 1100,
        "source": {"title": "GeeksforGeeks - Graph introduction", "url": "https://www.geeksforgeeks.org/dsa/introduction-to-graphs-data-structure-and-algorithm-tutorials/"},
        "text": "Sum of degrees in an undirected graph with 3 edges?",
        "answer": "6",
        "keywords": ["6"],
        "explanation": "Sum of degrees = 2|E|.",
    },
    {
        "id": "d-g1-adj",
        "module_id": "graphs1",
        "title": "Adj list vs matrix",
        "type": "mcq",
        "rating": 1200,
        "source": {"title": "GeeksforGeeks - Graph representation", "url": "https://www.geeksforgeeks.org/dsa/graph-and-its-representations/"},
        "text": "Sparse graph (n=1e5, m=2e5). Prefer:",
        "options": ["n x n adjacency matrix", "adjacency lists", "only an edge list with no lists", "Floyd table"],
        "answer": "adjacency lists",
        "explanation": "Matrix is n^2 memory. Lists are O(n+m).",
    },
    {
        "id": "d-g1-bfs",
        "module_id": "graphs1",
        "title": "BFS hop count",
        "type": "short",
        "rating": 1200,
        "source": {"title": "GeeksforGeeks - BFS", "url": "https://www.geeksforgeeks.org/dsa/breadth-first-search-or-bfs-for-a-graph/"},
        "text": "Unweighted path 1-2-3-4. BFS distance from 1 to 4?",
        "answer": "3",
        "keywords": ["3"],
        "explanation": "BFS on unweighted graphs gives shortest hop count.",
    },
    {
        "id": "d-g2-kruskal",
        "module_id": "graphs2",
        "title": "Kruskal sort key",
        "type": "mcq",
        "rating": 1500,
        "source": {"title": "GeeksforGeeks - Kruskal MST", "url": "https://www.geeksforgeeks.org/dsa/kruskals-minimum-spanning-tree-algorithm-greedy-algo-2/"},
        "text": "Kruskal builds an MST by adding edges in order of:",
        "options": ["weight increasing, skip if they form a cycle", "weight decreasing", "vertex id", "DFS tree order"],
        "answer": "weight increasing, skip if they form a cycle",
        "explanation": "DSU detects the cycle. Prim grows from a vertex instead.",
    },
    {
        "id": "d-g2-topo",
        "module_id": "graphs2",
        "title": "Topo order needs",
        "type": "mcq",
        "rating": 1500,
        "source": {"title": "GeeksforGeeks - Topological sort", "url": "https://www.geeksforgeeks.org/dsa/topological-sorting/"},
        "text": "Kahn / DFS topological order exists if the graph is:",
        "options": ["any undirected graph", "a DAG", "a graph with a cycle", "a complete graph only"],
        "answer": "a DAG",
        "explanation": "A cycle blocks a total order of prerequisites.",
    },
    {
        "id": "d-dp-lcs",
        "module_id": "dp",
        "title": "LCS length",
        "type": "short",
        "rating": 1500,
        "source": {"title": "GeeksforGeeks - LCS", "url": "https://www.geeksforgeeks.org/dsa/longest-common-subsequence-dp-4/"},
        "text": "LCS length of ABCD and ACBD?",
        "answer": "3",
        "keywords": ["3"],
        "explanation": "ABD or ACD. Length 3.",
    },
    {
        "id": "d-dp-lis",
        "module_id": "dp",
        "title": "LIS length",
        "type": "short",
        "rating": 1500,
        "source": {"title": "GeeksforGeeks - LIS", "url": "https://www.geeksforgeeks.org/dsa/longest-increasing-subsequence-dp-3/"},
        "text": "Length of a longest increasing subsequence of [3, 1, 2, 4]?",
        "answer": "3",
        "keywords": ["3"],
        "explanation": "1,2,4 or 3,4. Best is 3.",
    },
    {
        "id": "d-dp-coin",
        "module_id": "dp",
        "title": "Coin change count",
        "type": "code",
        "rating": 1400,
        "source": {"title": "GeeksforGeeks - Coin change", "url": "https://www.geeksforgeeks.org/dsa/coin-change-dp-7/"},
        "text": "Coins [1, 3, 4], unlimited. Read n. Print ordered ways to make n (1+3 and 3+1 both count). n <= 20.",
        "sample": {"stdin": "4\n", "stdout": "4\n"},
        "starter": "n = int(input())\ncoins = [1, 3, 4]\n",
        "tests": [
            {"stdin": "4\n", "stdout": "4\n"},
            {"stdin": "1\n", "stdout": "1\n"},
            {"stdin": "3\n", "stdout": "2\n", "hidden": True},
        ],
        "explanation": "dp[0]=1; for x in 1..n: for c in coins: if x>=c: dp[x]+=dp[x-c]. n=4 has 4 ordered ways.",
    },
    {
        "id": "d-ts-kmp2",
        "module_id": "trees-str",
        "title": "KMP mismatch jump",
        "type": "mcq",
        "rating": 1500,
        "source": {"title": "GeeksforGeeks - KMP", "url": "https://www.geeksforgeeks.org/dsa/kmp-algorithm-for-pattern-searching/"},
        "text": "KMP uses the prefix function so that on a mismatch you:",
        "options": ["restart the pattern at 0 always", "slide using pi[j-1] instead of j=0 every time", "rebuild the text", "sort the pattern"],
        "answer": "slide using pi[j-1] instead of j=0 every time",
        "explanation": "That is the linear-time trick.",
    },
    {
        "id": "d-ts-lca",
        "module_id": "trees-str",
        "title": "Tree edge count",
        "type": "short",
        "rating": 1300,
        "source": {"title": "GeeksforGeeks - Trees", "url": "https://www.geeksforgeeks.org/dsa/binary-tree-data-structure/"},
        "text": "A tree with n=5 nodes has how many edges?",
        "answer": "4",
        "keywords": ["4"],
        "explanation": "A tree on n nodes has n-1 edges.",
    },
    {
        "id": "d-ts-zfun",
        "module_id": "trees-str",
        "title": "Z-function idea",
        "type": "mcq",
        "rating": 1600,
        "source": {"title": "GeeksforGeeks - Z algorithm", "url": "https://www.geeksforgeeks.org/dsa/z-algorithm-linear-time-pattern-searching-algorithm/"},
        "text": "Z[i] is the longest prefix of the string that also starts at i. Z[0] is usually:",
        "options": ["0 or unused / n by convention", "always 1", "the last character", "hash of s"],
        "answer": "0 or unused / n by convention",
        "explanation": "People set Z[0]=0 or Z[0]=n. The useful values are i>0.",
    },
]
